import { describe, expect, it } from 'vitest';
import { buildResourceAwareGuidance } from '../resourceAwareGuidance';
const equipment = (equipmentId: string, kind: string, facts: any[] = [], limitations: string[] = []) => ({ schemaVersion: 1, equipmentId, kind, label: equipmentId, facts, limitations, state: 'active', createdAtUtc: '2026-09-01T00:00:00.000Z', updatedAtUtc: '2026-09-01T00:00:00.000Z' });
const fact = (key: string, value: number) => ({ key, value, source: 'operator_entered' });
const brief = (items?: any[], deployment: any = { geometry: 'inverted_v', heightCategory: '15_to_30_ft' }) => ({ schemaVersion: 2, missionWindow: { start: '2026-09-20T12:00:00.000Z', midpoint: '2026-09-20T14:00:00.000Z', end: '2026-09-20T16:00:00.000Z' }, station: { deployment }, ...(items ? { loadoutSnapshot: { schemaVersion: 1, loadoutId: 'field', loadoutName: 'Field', capturedAtUtc: '2026-09-16T00:00:00.000Z', provenance: 'operator_committed', limitations: [], items } } : {}) } as any);
const item = (record: any, quantity = 1) => ({ item: { equipmentId: record.equipmentId, role: record.kind, quantity }, equipment: record });
describe('resource-aware mission guidance', () => {
  it('keeps missing inputs unknown', () => { const result = buildResourceAwareGuidance(brief(undefined, null), null); expect(result.findings.map(value => [value.id, value.status])).toEqual([['loadout-coverage', 'unknown'], ['station-endurance', 'unknown'], ['weather-concerns', 'unknown'], ['antenna-deployment', 'unknown'], ['operator-contingencies', 'unknown']]); expect(result.findings[1].limitation).toContain('will not derive endurance'); });
  it('calculates endurance only from explicit operator facts and quantities', () => { const radio = equipment('radio', 'radio', [fact('expected_average_draw_w', 20)]); const result = buildResourceAwareGuidance(brief([item(radio), item(equipment('antenna', 'antenna')), item(equipment('battery', 'battery', [fact('usable_capacity_wh', 60)]), 2)]), null); expect(result.findings[0].status).toBe('supported'); expect(result.findings[1]).toMatchObject({ status: 'supported', conclusion: 'Operator facts estimate 6 hours of station endurance for a 4-hour mission.' }); });
  it('flags endurance and bounded weather thresholds without calling them hazards', () => { const items = [item(equipment('radio', 'radio', [fact('expected_average_draw_w', 30)])), item(equipment('antenna', 'antenna')), item(equipment('battery', 'battery', [fact('usable_capacity_wh', 60)]))]; const result = buildResourceAwareGuidance(brief(items), { freshness: 'live', hourly: [{ precipitationProbability: 85, windGustMph: 31, temperatureF: 65 }] }); expect(result.findings[1].status).toBe('attention'); expect(result.findings[2].conclusion).toContain('85% precipitation probability'); expect(result.findings[2].conclusion).toContain('31 mph gusts'); expect(result.findings[2].limitation).toContain('not hazard declarations'); });
  it('is deterministic and preserves operator limitations', () => { const input = brief([item(equipment('radio', 'radio')), item(equipment('antenna', 'antenna', [], ['Requires two supports.'])), item(equipment('power', 'power_system'))]); const first = buildResourceAwareGuidance(input, null); expect(buildResourceAwareGuidance(input, null)).toEqual(first); expect(first.findings[3]).toMatchObject({ status: 'attention', sourceState: 'operator_limitation' }); expect(first.findings[4].basis).toContain('Requires two supports.'); });
});
