import type { EquipmentKind, EquipmentRecord, LoadoutRecord } from './domain';

export interface EquipmentDraft { readonly kind: EquipmentKind; readonly label: string; readonly manufacturer?: string; readonly model?: string; readonly notes?: string; readonly facts: readonly { readonly key: string; readonly value: string | number | boolean; readonly unit?: string; readonly source: 'operator_entered' }[]; readonly limitations: readonly string[]; }
export interface LoadoutDraft { readonly name: string; readonly description?: string; readonly items: readonly { readonly equipmentId: string; readonly role: string; readonly quantity: number; readonly notes?: string }[]; readonly limitations: readonly string[]; }
export interface EquipmentWorkspaceData { readonly equipment: readonly EquipmentRecord[]; readonly loadouts: readonly LoadoutRecord[]; }

export async function fetchEquipmentWorkspace(fetcher: typeof fetch = fetch): Promise<EquipmentWorkspaceData> { const [inventoryResponse, loadoutResponse] = await Promise.all([fetcher('/api/equipment'), fetcher('/api/loadouts')]); if (!inventoryResponse.ok || !loadoutResponse.ok) throw new Error('Equipment records are unavailable.'); const inventory = await inventoryResponse.json(); const loadouts = await loadoutResponse.json(); return { equipment: inventory.equipment ?? [], loadouts: loadouts.loadouts ?? [] }; }
export async function saveEquipment(draft: EquipmentDraft, equipmentId?: string, fetcher: typeof fetch = fetch): Promise<void> { await mutation(equipmentId ? `/api/equipment/${equipmentId}` : '/api/equipment', equipmentId ? 'PATCH' : 'POST', draft, fetcher); }
export async function transitionEquipment(equipmentId: string, restore: boolean, fetcher: typeof fetch = fetch): Promise<void> { await mutation(`/api/equipment/${equipmentId}${restore ? '/restore' : ''}`, restore ? 'POST' : 'DELETE', undefined, fetcher); }
export async function saveLoadout(draft: LoadoutDraft, loadoutId?: string, fetcher: typeof fetch = fetch): Promise<void> { await mutation(loadoutId ? `/api/loadouts/${loadoutId}` : '/api/loadouts', loadoutId ? 'PATCH' : 'POST', draft, fetcher); }
export async function transitionLoadout(loadoutId: string, restore: boolean, fetcher: typeof fetch = fetch): Promise<void> { await mutation(`/api/loadouts/${loadoutId}${restore ? '/restore' : ''}`, restore ? 'POST' : 'DELETE', undefined, fetcher); }
async function mutation(url: string, method: string, body: unknown, fetcher: typeof fetch): Promise<void> { const response = await fetcher(url, { method, headers: body === undefined ? undefined : { 'Content-Type': 'application/json' }, body: body === undefined ? undefined : JSON.stringify(body) }); if (!response.ok) { const value = await response.json().catch(() => ({})); throw new Error(value.message || 'The equipment change could not be saved.'); } }
