import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { FIELD_READINESS_CHECKLIST_MAX_RETAINED, createFieldReadinessChecklist, normalizeFieldReadinessChecklist, resetFieldReadinessChecklist, updateFieldReadinessChecklistItem, type FieldReadinessChecklist } from './fieldReadinessChecklist';

export const FIELD_READINESS_CHECKLIST_STORE_VERSION = 1 as const;
export const FIELD_READINESS_CHECKLIST_STORE_FILE_NAME = 'field-readiness-checklists.json';
export type FieldReadinessChecklistStoreDiagnosticCode = 'missing' | 'corrupt' | 'unsupported_store_version' | 'invalid_checklist' | 'io_error';
export interface FieldReadinessChecklistStoreDiagnostic { readonly code: FieldReadinessChecklistStoreDiagnosticCode; readonly message: string; readonly checklistId?: string; }
export interface FieldReadinessChecklistStoreReadResult { readonly status: 'missing' | 'loaded' | 'invalid' | 'ioError'; readonly checklists: readonly FieldReadinessChecklist[]; readonly diagnostics: readonly FieldReadinessChecklistStoreDiagnostic[]; }
export type FieldReadinessChecklistStoreGetResult = { readonly status: 'found'; readonly checklist: FieldReadinessChecklist; readonly diagnostics: readonly FieldReadinessChecklistStoreDiagnostic[] } | { readonly status: 'notFound'; readonly diagnostics: readonly FieldReadinessChecklistStoreDiagnostic[] };
export type FieldReadinessChecklistStoreDeleteResult = { readonly status: 'deleted'; readonly checklist: FieldReadinessChecklist; readonly diagnostics: readonly FieldReadinessChecklistStoreDiagnostic[] } | { readonly status: 'notFound'; readonly diagnostics: readonly FieldReadinessChecklistStoreDiagnostic[] };
export type FieldReadinessChecklistStoreCreateResult = { readonly status: 'created' | 'existing'; readonly checklist: FieldReadinessChecklist; readonly diagnostics: readonly FieldReadinessChecklistStoreDiagnostic[] };
interface StoreDocument { readonly storeVersion: typeof FIELD_READINESS_CHECKLIST_STORE_VERSION; readonly checklists: readonly FieldReadinessChecklist[]; }
interface FileSystem { readFileSync(filePath: string, encoding: 'utf8'): string; writeFileSync(filePath: string, content: string, options: { encoding: 'utf8'; flag: 'wx' }): void; renameSync(oldPath: string, newPath: string): void; mkdirSync(directory: string, options: { recursive: true }): unknown; rmSync(filePath: string, options: { force: true }): void; }

export function getDefaultFieldReadinessChecklistPath(environment: NodeJS.ProcessEnv = process.env, homeDirectory = os.homedir()): string { const localAppData = environment.LOCALAPPDATA || path.join(homeDirectory, 'AppData', 'Local'); return path.join(localAppData, 'FieldOpsDashboard', FIELD_READINESS_CHECKLIST_STORE_FILE_NAME); }

export class FieldReadinessChecklistStore {
  private readonly fileSystem: FileSystem;
  constructor(private readonly filePath: string, private readonly options: { readonly fileSystem?: FileSystem; readonly now?: () => Date; readonly createId?: () => string } = {}) { this.fileSystem = options.fileSystem ?? fs as unknown as FileSystem; }
  load(): FieldReadinessChecklistStoreReadResult { let json: string; try { json = this.fileSystem.readFileSync(this.filePath, 'utf8'); } catch (error) { if (isNodeError(error) && error.code === 'ENOENT') return { status: 'missing', checklists: [], diagnostics: [{ code: 'missing', message: 'No field readiness checklist store exists yet.' }] }; return { status: 'ioError', checklists: [], diagnostics: [{ code: 'io_error', message: 'The field readiness checklist store could not be read.' }] }; } let parsed: unknown; try { parsed = JSON.parse(json); } catch { return { status: 'invalid', checklists: [], diagnostics: [{ code: 'corrupt', message: 'The field readiness checklist store contains invalid JSON.' }] }; } if (!isRecord(parsed) || parsed.storeVersion !== 1 || !Array.isArray(parsed.checklists)) { const code = isRecord(parsed) && parsed.storeVersion !== 1 ? 'unsupported_store_version' : 'corrupt'; return { status: 'invalid', checklists: [], diagnostics: [{ code, message: 'The field readiness checklist store wrapper is unsupported or malformed.' }] }; } const checklists: FieldReadinessChecklist[] = []; const diagnostics: FieldReadinessChecklistStoreDiagnostic[] = []; const briefIds = new Set<string>(); const checklistIds = new Set<string>(); for (const candidate of parsed.checklists) { const normalized = normalizeFieldReadinessChecklist(candidate); const checklistId = isRecord(candidate) && typeof candidate.checklistId === 'string' ? candidate.checklistId : undefined; if (!normalized.valid || !normalized.checklist || checklistIds.has(normalized.checklist?.checklistId ?? checklistId ?? '') || briefIds.has(normalized.checklist?.briefId ?? '')) diagnostics.push({ code: 'invalid_checklist', message: 'A stored field readiness checklist was skipped because it is invalid or duplicated.', ...(checklistId ? { checklistId } : {}) }); else { checklists.push(normalized.checklist); checklistIds.add(normalized.checklist.checklistId); briefIds.add(normalized.checklist.briefId); } } return { status: 'loaded', checklists: orderChecklists(checklists).slice(0, FIELD_READINESS_CHECKLIST_MAX_RETAINED), diagnostics }; }
  list(): FieldReadinessChecklistStoreReadResult { return this.load(); }
  get(checklistId: string): FieldReadinessChecklistStoreGetResult { const loaded = this.load(); const checklist = loaded.checklists.find(candidate => candidate.checklistId === checklistId); return checklist ? { status: 'found', checklist, diagnostics: loaded.diagnostics } : { status: 'notFound', diagnostics: loaded.diagnostics }; }
  getByBriefId(briefId: string): FieldReadinessChecklistStoreReadResult { const loaded = this.load(); return { ...loaded, checklists: loaded.checklists.filter(checklist => checklist.briefId === briefId) }; }
  createForBrief(briefId: string): FieldReadinessChecklistStoreCreateResult { const loaded = this.load(); const existing = loaded.checklists.find(checklist => checklist.briefId === briefId); if (existing) return { status: 'existing', checklist: existing, diagnostics: loaded.diagnostics }; const checklist = createFieldReadinessChecklist({ briefId }, this.options); this.write({ storeVersion: 1, checklists: orderChecklists([checklist, ...loaded.checklists]).slice(0, FIELD_READINESS_CHECKLIST_MAX_RETAINED) }); return { status: 'created', checklist, diagnostics: loaded.diagnostics }; }
  updateItem(checklistId: string, itemId: string, completed: boolean): { readonly checklist: FieldReadinessChecklist; readonly diagnostics: readonly FieldReadinessChecklistStoreDiagnostic[] } { const loaded = this.load(); const existing = loaded.checklists.find(checklist => checklist.checklistId === checklistId); if (!existing) throw new Error(`Field readiness checklist ${checklistId} was not found.`); const checklist = updateFieldReadinessChecklistItem(existing, itemId, completed, this.options); this.write({ storeVersion: 1, checklists: orderChecklists(loaded.checklists.map(candidate => candidate.checklistId === checklistId ? checklist : candidate)) }); return { checklist, diagnostics: loaded.diagnostics }; }
  reset(checklistId: string): { readonly checklist: FieldReadinessChecklist; readonly diagnostics: readonly FieldReadinessChecklistStoreDiagnostic[] } { const loaded = this.load(); const existing = loaded.checklists.find(checklist => checklist.checklistId === checklistId); if (!existing) throw new Error(`Field readiness checklist ${checklistId} was not found.`); const checklist = resetFieldReadinessChecklist(existing, this.options); this.write({ storeVersion: 1, checklists: orderChecklists(loaded.checklists.map(candidate => candidate.checklistId === checklistId ? checklist : candidate)) }); return { checklist, diagnostics: loaded.diagnostics }; }
  delete(checklistId: string): FieldReadinessChecklistStoreDeleteResult { const loaded = this.load(); const checklist = loaded.checklists.find(candidate => candidate.checklistId === checklistId); if (!checklist) return { status: 'notFound', diagnostics: loaded.diagnostics }; this.write({ storeVersion: 1, checklists: loaded.checklists.filter(candidate => candidate.checklistId !== checklistId) }); return { status: 'deleted', checklist, diagnostics: loaded.diagnostics }; }
  private write(document: StoreDocument): void { const directory = path.dirname(this.filePath); this.fileSystem.mkdirSync(directory, { recursive: true }); const temporaryPath = `${this.filePath}.${process.pid}.${Date.now()}.${Math.random().toString(16).slice(2)}.tmp`; try { this.fileSystem.writeFileSync(temporaryPath, `${JSON.stringify(document, null, 2)}\n`, { encoding: 'utf8', flag: 'wx' }); try { this.fileSystem.renameSync(temporaryPath, this.filePath); } catch (error) { if (!isNodeError(error) || (error.code !== 'EEXIST' && error.code !== 'EPERM')) throw error; this.fileSystem.rmSync(this.filePath, { force: true }); this.fileSystem.renameSync(temporaryPath, this.filePath); } } finally { try { this.fileSystem.rmSync(temporaryPath, { force: true }); } catch { /* best-effort temporary cleanup */ } } }
}
function orderChecklists(checklists: readonly FieldReadinessChecklist[]): FieldReadinessChecklist[] { return [...checklists].sort((left, right) => right.updatedAtUtc.localeCompare(left.updatedAtUtc) || right.checklistId.localeCompare(left.checklistId)); }
function isRecord(input: unknown): input is Record<string, any> { return typeof input === 'object' && input !== null && !Array.isArray(input); }
function isNodeError(error: unknown): error is NodeJS.ErrnoException { return error instanceof Error; }