import * as net from 'node:net';

export const LOCATION_TELEMETRY_PIPE = '\\\\.\\pipe\\FieldOps.LocationTelemetry.v1';
export const LOCATION_TELEMETRY_MAX_FRAME = 256 * 1024;
export type LocationTelemetry = { latitude:number|null; longitude:number|null; altitude:number|null; horizontalAccuracy:number|null; speed:number|null; heading:number|null; timestampUtc:string|null; status:'Available'|'NoFix'|'Initializing'|'Unavailable'|'Error'; satellites:number|null; hdop:number|null; fixQuality:number|null; source:string|null };
export type GnssTimeEvidence = { status:'Available'|'Unavailable'|'Malformed'; timestampUtc:string|null; sentenceType:string; error?:string|null };
export type ClockSynchronizationEvidence = { status:'Synchronized'|'NotSynchronized'|'Unknown'|'Unavailable'|'Error'; error:'None'|'ConfirmationRequired'|'GnssUnavailable'|'GnssStaleOrMalformed'|'UnsafeOffset'|'PrivilegeUnavailable'|'NativeFailure'|'UnsupportedPlatform'; gnssTime:GnssTimeEvidence; lastSuccessfulSynchronizationUtc:string|null; offsetBeforeSynchronizationSeconds:number|null; attemptMessage:string|null };
const request = Buffer.from(JSON.stringify({ command: 'GetLocation' }));
const empty = (status: LocationTelemetry['status'], error?: string) => ({ latitude:null, longitude:null, altitude:null, horizontalAccuracy:null, speed:null, heading:null, timestampUtc:null, status, satellites:null, hdop:null, fixQuality:null, source:'SerialNmea', ...(error ? { error } : {}) });
const finiteOrNull = (v: unknown): v is number|null => v === null || (typeof v === 'number' && Number.isFinite(v));
export function parseLocationTelemetryFrame(frame: Buffer): LocationTelemetry { if(frame.length<4)return empty('Error'); const n=frame.readInt32LE(0); if(n<=0||n>LOCATION_TELEMETRY_MAX_FRAME||frame.length!==n+4)return empty('Error'); try { const v=JSON.parse(frame.subarray(4).toString()) as Record<string,unknown>; const numeric=['latitude','longitude','altitude','horizontalAccuracy','speed','heading','satellites','hdop','fixQuality']; if(!v||typeof v!=='object'||!['Available','NoFix','Initializing','Unavailable','Error'].includes(String(v.status))||numeric.some(k=>!finiteOrNull(v[k]))|| (v.latitude!==null&&(v.latitude as number)<-90||(v.latitude!==null&&(v.latitude as number)>90)) || (v.longitude!==null&&(v.longitude as number)<-180||(v.longitude!==null&&(v.longitude as number)>180)) || (v.timestampUtc!==null&&typeof v.timestampUtc!=='string') || (v.timestampUtc!==null&&Number.isNaN(Date.parse(v.timestampUtc as string))) || (v.source!==null&&typeof v.source!=='string')) return empty('Error'); if(v.status==='Available'&&(v.latitude===null||v.longitude===null))return empty('Error'); return v as LocationTelemetry; } catch { return empty('Error'); } }
export function readLocationTelemetryPipe(timeoutMs=15000): Promise<LocationTelemetry> { if(process.platform!=='win32')return Promise.resolve(empty('Unavailable')); return new Promise(resolve=>{const s=net.connect(LOCATION_TELEMETRY_PIPE);let b=Buffer.alloc(0),done=false;const finish=(v:LocationTelemetry)=>{if(done)return;done=true;clearTimeout(t);s.removeAllListeners();s.destroy();resolve(v)};const t=setTimeout(()=>finish(empty('Unavailable')),timeoutMs);s.once('connect',()=>{const f=Buffer.alloc(4+request.length);f.writeInt32LE(request.length);request.copy(f,4);s.write(f)});s.on('data',c=>{b=Buffer.concat([b,c]);if(b.length>LOCATION_TELEMETRY_MAX_FRAME+4)return finish(empty('Error'));if(b.length>=4){const n=b.readInt32LE(0);if(n>0&&n<=LOCATION_TELEMETRY_MAX_FRAME&&b.length>=n+4)finish(parseLocationTelemetryFrame(b))}});s.once('error',()=>finish(empty('Unavailable')));s.once('close',()=>{if(!done)finish(empty('Unavailable'))})}) }

const emptyGnssTime = (status: GnssTimeEvidence['status'], error?: string): GnssTimeEvidence => ({ status, timestampUtc: null, sentenceType: 'RMC', ...(error ? { error } : {}) });
const emptyClock = (error?: string): ClockSynchronizationEvidence => ({ status: 'Unknown', error: 'None', gnssTime: emptyGnssTime('Unavailable', error), lastSuccessfulSynchronizationUtc: null, offsetBeforeSynchronizationSeconds: null, attemptMessage: error ?? null });
function readClockPipe(command: 'GetGnssTime' | 'GetClockStatus' | 'SynchronizeClock', confirmed = false, timeoutMs = 15000): Promise<GnssTimeEvidence | ClockSynchronizationEvidence> { if(process.platform!=='win32')return Promise.resolve(command === 'GetGnssTime' ? emptyGnssTime('Unavailable') : emptyClock('The FieldOps Agent is unavailable on this platform.')); return new Promise(resolve=>{const s=net.connect(LOCATION_TELEMETRY_PIPE);let b=Buffer.alloc(0),done=false;const finish=(v: GnssTimeEvidence | ClockSynchronizationEvidence)=>{if(done)return;done=true;clearTimeout(t);s.removeAllListeners();s.destroy();resolve(v)};const t=setTimeout(()=>finish(command === 'GetGnssTime' ? emptyGnssTime('Unavailable') : emptyClock('The FieldOps Agent did not respond.')),timeoutMs);const payload=Buffer.from(JSON.stringify({ command, confirmed }));s.once('connect',()=>{const f=Buffer.alloc(4+payload.length);f.writeInt32LE(payload.length);payload.copy(f,4);s.write(f)});s.on('data',c=>{b=Buffer.concat([b,c]);if(b.length>LOCATION_TELEMETRY_MAX_FRAME+4)return finish(command === 'GetGnssTime' ? emptyGnssTime('Unavailable') : emptyClock('Invalid Agent response.'));if(b.length>=4){const n=b.readInt32LE(0);if(n>0&&n<=LOCATION_TELEMETRY_MAX_FRAME&&b.length>=n+4){try{const value=JSON.parse(b.subarray(4,n+4).toString());finish(value);}catch{finish(command === 'GetGnssTime' ? emptyGnssTime('Unavailable') : emptyClock('Invalid Agent response.'));}}}});s.once('error',()=>finish(command === 'GetGnssTime' ? emptyGnssTime('Unavailable') : emptyClock('The FieldOps Agent is unavailable.')));s.once('close',()=>{if(!done)finish(command === 'GetGnssTime' ? emptyGnssTime('Unavailable') : emptyClock('The FieldOps Agent is unavailable.'))})}) }
export const readGnssTimePipe = (timeoutMs = 15000) => readClockPipe('GetGnssTime', false, timeoutMs) as Promise<GnssTimeEvidence>;
export const readClockStatusPipe = (timeoutMs = 15000) => readClockPipe('GetClockStatus', false, timeoutMs) as Promise<ClockSynchronizationEvidence>;
export const synchronizeClockPipe = (confirmed: boolean, timeoutMs = 15000) => readClockPipe('SynchronizeClock', confirmed, timeoutMs) as Promise<ClockSynchronizationEvidence>;
