import * as net from 'node:net';

export const LOCATION_TELEMETRY_PIPE = '\\\\.\\pipe\\FieldOps.LocationTelemetry.v1';
export const LOCATION_TELEMETRY_MAX_FRAME = 256 * 1024;
export type LocationTelemetry = { latitude:number|null; longitude:number|null; altitude:number|null; horizontalAccuracy:number|null; speed:number|null; heading:number|null; timestampUtc:string|null; status:'Available'|'NoFix'|'Initializing'|'Unavailable'|'Error'; satellites:number|null; hdop:number|null; fixQuality:number|null; source:string|null };
const request = Buffer.from(JSON.stringify({ command: 'GetLocation' }));
const empty = (status: LocationTelemetry['status'], error?: string) => ({ latitude:null, longitude:null, altitude:null, horizontalAccuracy:null, speed:null, heading:null, timestampUtc:null, status, satellites:null, hdop:null, fixQuality:null, source:'SerialNmea', ...(error ? { error } : {}) });
export function parseLocationTelemetryFrame(frame: Buffer): LocationTelemetry { if(frame.length<4)return empty('Error'); const n=frame.readInt32LE(0); if(n<=0||n>LOCATION_TELEMETRY_MAX_FRAME||frame.length!==n+4)return empty('Error'); try { const v=JSON.parse(frame.subarray(4).toString()); if(!v||typeof v!=='object'||!['Available','NoFix','Initializing','Unavailable','Error'].includes(v.status))return empty('Error'); return v as LocationTelemetry; } catch { return empty('Error'); } }
export function readLocationTelemetryPipe(timeoutMs=5000): Promise<LocationTelemetry> { if(process.platform!=='win32')return Promise.resolve(empty('Unavailable')); return new Promise(resolve=>{const s=net.connect(LOCATION_TELEMETRY_PIPE);let b=Buffer.alloc(0),done=false;const finish=(v:LocationTelemetry)=>{if(done)return;done=true;clearTimeout(t);s.destroy();resolve(v)};const t=setTimeout(()=>finish(empty('Unavailable')),timeoutMs);s.once('connect',()=>{const f=Buffer.alloc(4+request.length);f.writeInt32LE(request.length);request.copy(f,4);s.write(f)});s.on('data',c=>{b=Buffer.concat([b,c]);if(b.length>LOCATION_TELEMETRY_MAX_FRAME+4)return finish(empty('Error'));if(b.length>=4){const n=b.readInt32LE(0);if(n>0&&n<=LOCATION_TELEMETRY_MAX_FRAME&&b.length>=n+4)finish(parseLocationTelemetryFrame(b))}});s.once('error',()=>finish(empty('Unavailable')));s.once('close',()=>{if(!done)finish(empty('Unavailable'))})}) }
