import { parseCoordinates } from '../src/location/coordinates';
import type { SmartDeployBriefV2 } from './smartDeployBrief';

export const MISSION_FORECAST_SCHEMA_VERSION = 2 as const;
export const MISSION_FORECAST_PREVIOUS_SCHEMA_VERSION = 1 as const;
export const MISSION_FORECAST_HOURLY_PRESENTATION_MAX_HOURS = 12;
export const MISSION_FORECAST_PROVIDER_TIMEOUT_MS = 10_000;
export const MISSION_FORECAST_PROVIDER_ID = 'open-meteo-mission-forecast';

export type MissionForecastStatus = 'live' | 'outside_provider_horizon' | 'planned_coordinates_invalid' | 'provider_unavailable' | 'provider_unusable';
export type MissionForecastCoverageStatus = 'complete' | 'partial' | 'outside_provider_horizon';
export type MissionForecastFreshness = 'live' | 'retained' | 'stale';
export interface MissionForecastHourlyObservation { readonly startsAtUtc: string; readonly endsAtUtc: string; readonly missionApplicable: boolean; readonly temperatureF: number; readonly precipitationProbability: number; readonly windSpeedMph: number; readonly windDirectionDegrees: number; readonly windDirection: string; readonly windGustMph?: number; readonly weatherCode: number; readonly condition: string; }
export type MissionForecastPeriod = MissionForecastHourlyObservation;
export interface MissionForecastOperatingPeriod { readonly periodId: string; readonly label: string; readonly startsAtUtc: string; readonly endsAtUtc: string; readonly timezoneLabel: 'UTC'; readonly expectedHourlySlotCount: number; readonly observedHourlySlotCount: number; readonly missingHourlySlotCount: number; readonly coverageStatus: MissionForecastCoverageStatus; readonly temperatureMinF: number | null; readonly temperatureMaxF: number | null; readonly precipitationProbabilityMax: number | null; readonly sustainedWindMinMph: number | null; readonly sustainedWindMaxMph: number | null; readonly windGustMaxMph?: number; readonly significantCondition: string | null; readonly provider: 'Open-Meteo'; readonly retrievedAtUtc: string; readonly freshness: MissionForecastFreshness; readonly limitations: readonly string[]; readonly hourlyObservationIndexes: readonly number[]; readonly hourlyObservationTimestampsUtc: readonly string[]; }
export interface MissionForecastRecord { readonly schemaVersion: typeof MISSION_FORECAST_SCHEMA_VERSION; readonly briefId: string; readonly activation: { readonly program: string; readonly reference: string }; readonly plannedSite: { readonly latitude: number; readonly longitude: number; readonly gridSquare: string | null; readonly provenance: string }; readonly missionWindow: { readonly start: string; readonly end: string }; readonly provider: { readonly id: typeof MISSION_FORECAST_PROVIDER_ID; readonly name: 'Open-Meteo'; readonly timezone: 'UTC' }; readonly retrievedAtUtc: string; readonly hourly: readonly MissionForecastHourlyObservation[]; readonly periods: readonly MissionForecastPeriod[]; readonly operatingPeriods: readonly MissionForecastOperatingPeriod[]; readonly presentation: { readonly mode: 'hourly' | 'aggregated'; readonly hourlyThresholdHours: number; readonly boundaryStrategy: 'utc_fixed_six_hour_periods' }; readonly status: 'live'; readonly freshness: MissionForecastFreshness; readonly coverageStatus: MissionForecastCoverageStatus; readonly sourceUrl: string; readonly limitations: readonly string[]; readonly diagnostics: readonly string[]; readonly updatedAtUtc: string; }
export interface MissionForecastProviderOptions { readonly fetcher?: typeof fetch; readonly now?: Date; readonly timeoutMs?: number; }
export interface MissionForecastRetrieval { readonly status: MissionForecastStatus; readonly record: MissionForecastRecord | null; readonly message: string; }

export async function retrieveMissionForecast(brief: SmartDeployBriefV2, options: MissionForecastProviderOptions = {}): Promise<MissionForecastRetrieval> {
  const coordinates = brief.plannedOperatingSite.location.coordinates
    ? parseCoordinates(brief.plannedOperatingSite.location.coordinates.lat, brief.plannedOperatingSite.location.coordinates.lon)
    : null;
  const start = Date.parse(brief.missionWindow.start);
  const end = Date.parse(brief.missionWindow.end);
  const now = options.now ?? new Date();
  if (!coordinates || !Number.isFinite(start) || !Number.isFinite(end) || end < start || !Number.isFinite(now.getTime())) return { status: 'planned_coordinates_invalid', record: null, message: 'The retained planned site or mission window is invalid; no forecast request was made.' };
  const retrievedAtUtc = now.toISOString();
  const startDate = new Date(start).toISOString().slice(0, 10);
  const endDate = new Date(end).toISOString().slice(0, 10);
  const sourceUrl = `https://api.open-meteo.com/v1/forecast?latitude=${coordinates.lat}&longitude=${coordinates.lon}&start_date=${startDate}&end_date=${endDate}&hourly=temperature_2m,precipitation_probability,wind_speed_10m,wind_direction_10m,wind_gusts_10m,weather_code&temperature_unit=fahrenheit&wind_speed_unit=mph&timezone=UTC`;
  try {
    const response = await fetchWithTimeout(options.fetcher ?? fetch, options.timeoutMs ?? MISSION_FORECAST_PROVIDER_TIMEOUT_MS)(sourceUrl);
    if (!response.ok) return { status: 'provider_unavailable', record: null, message: 'The terrestrial forecast provider is unavailable.' };
    const body = await response.json() as Record<string, unknown>;
    const sourceHourly = body.hourly;
    if (!isRecord(sourceHourly) || !Array.isArray(sourceHourly.time) || !Array.isArray(sourceHourly.temperature_2m) || !Array.isArray(sourceHourly.precipitation_probability) || !Array.isArray(sourceHourly.wind_speed_10m) || !Array.isArray(sourceHourly.wind_direction_10m) || !Array.isArray(sourceHourly.weather_code)) return unusable();
    const requiredArrays = [sourceHourly.time, sourceHourly.temperature_2m, sourceHourly.precipitation_probability, sourceHourly.wind_speed_10m, sourceHourly.wind_direction_10m, sourceHourly.weather_code];
    if (requiredArrays.some(array => array.length !== sourceHourly.time.length) || (sourceHourly.wind_gusts_10m !== undefined && (!Array.isArray(sourceHourly.wind_gusts_10m) || sourceHourly.wind_gusts_10m.length !== sourceHourly.time.length))) return unusable();
    const hourly: MissionForecastHourlyObservation[] = [];
    for (let index = 0; index < sourceHourly.time.length; index += 1) {
      const periodStart = typeof sourceHourly.time[index] === 'string' ? parseProviderTimestamp(sourceHourly.time[index] as string) : Number.NaN;
      const temperature = sourceHourly.temperature_2m[index]; const precipitation = sourceHourly.precipitation_probability[index]; const windSpeed = sourceHourly.wind_speed_10m[index]; const windDirection = sourceHourly.wind_direction_10m[index]; const weatherCode = sourceHourly.weather_code[index]; const gust = Array.isArray(sourceHourly.wind_gusts_10m) ? sourceHourly.wind_gusts_10m[index] : undefined;
      if (!Number.isFinite(periodStart) || !finite(temperature) || !finite(precipitation) || !finite(windSpeed) || !finite(windDirection) || !finite(weatherCode) || (gust !== undefined && !finite(gust)) || precipitation < 0 || precipitation > 100 || windSpeed < 0 || windDirection < 0 || windDirection >= 360 || weatherCode < 0 || (gust !== undefined && gust < 0)) return unusable();
      const periodEnd = periodStart + 3_600_000;
      if (periodEnd <= start || periodStart > end) continue;
      hourly.push({ startsAtUtc: new Date(periodStart).toISOString(), endsAtUtc: new Date(periodEnd).toISOString(), missionApplicable: periodStart < end && periodEnd > start, temperatureF: temperature, precipitationProbability: precipitation, windSpeedMph: windSpeed, windDirectionDegrees: windDirection, windDirection: directionLabel(windDirection), ...(gust === undefined ? {} : { windGustMph: gust }), weatherCode, condition: conditionLabel(weatherCode) });
    }
    if (hourly.length === 0) return { status: 'outside_provider_horizon', record: null, message: 'The mission window is outside the terrestrial forecast provider horizon.' };
    const missionStart = new Date(start).toISOString(); const missionEnd = new Date(end).toISOString();
    const recordBase = { schemaVersion: MISSION_FORECAST_SCHEMA_VERSION, briefId: brief.briefId, activation: { program: brief.activation.program, reference: brief.activation.reference }, plannedSite: { latitude: coordinates.lat, longitude: coordinates.lon, gridSquare: brief.plannedOperatingSite.location.gridSquare, provenance: brief.plannedOperatingSite.location.provenance }, missionWindow: { start: missionStart, end: missionEnd }, provider: { id: MISSION_FORECAST_PROVIDER_ID, name: 'Open-Meteo' as const, timezone: 'UTC' as const }, retrievedAtUtc, hourly, status: 'live' as const, sourceUrl, limitations: ['Hourly provider values are retained without interpolation.', 'Forecast data does not establish site access, safety, or operating legality.'], diagnostics: [], updatedAtUtc: retrievedAtUtc };
    const periods = deriveMissionForecastPeriods(recordBase);
    const expectedHours = Math.ceil((end - start) / 3_600_000); const observedHours = hourly.filter(item => item.missionApplicable).length;
    return { status: 'live', message: 'Mission forecast retained.', record: { ...recordBase, periods: hourly, operatingPeriods: periods, presentation: { mode: (end - start) / 3_600_000 <= MISSION_FORECAST_HOURLY_PRESENTATION_MAX_HOURS ? 'hourly' : 'aggregated', hourlyThresholdHours: MISSION_FORECAST_HOURLY_PRESENTATION_MAX_HOURS, boundaryStrategy: 'utc_fixed_six_hour_periods' }, freshness: 'live', coverageStatus: observedHours >= expectedHours ? 'complete' : 'partial' } };
  } catch { return { status: 'provider_unavailable', record: null, message: 'The terrestrial forecast provider could not be reached.' }; }
}

export function deriveMissionForecastPeriods(record: Pick<MissionForecastRecord, 'missionWindow' | 'hourly' | 'provider' | 'retrievedAtUtc' | 'limitations'>): MissionForecastOperatingPeriod[] {
  const start = Date.parse(record.missionWindow.start); const end = Date.parse(record.missionWindow.end); const periods: MissionForecastPeriod[] = [];
  for (let cursor = Date.UTC(new Date(start).getUTCFullYear(), new Date(start).getUTCMonth(), new Date(start).getUTCDate(), Math.floor(new Date(start).getUTCHours() / 6) * 6); cursor < end; cursor += 6 * 3_600_000) {
    const periodStart = Math.max(cursor, start); const periodEnd = Math.min(cursor + 6 * 3_600_000, end); const indexes = record.hourly.map((item, index) => Date.parse(item.startsAtUtc) < periodEnd && Date.parse(item.endsAtUtc) > periodStart ? index : -1).filter(index => index >= 0); const observations = indexes.map(index => record.hourly[index]); const expected = Math.ceil((periodEnd - periodStart) / 3_600_000); const observed = observations.length; const missing = Math.max(0, expected - observed); const conditions = observations.map(item => ({ condition: item.condition, severity: conditionSeverity(item.weatherCode) })).sort((left, right) => right.severity - left.severity); const gusts = observations.flatMap(item => item.windGustMph === undefined ? [] : [item.windGustMph]);
    periods.push({ periodId: `utc-${new Date(cursor).toISOString().slice(0, 13)}`, label: utcPeriodLabel(cursor), startsAtUtc: new Date(periodStart).toISOString(), endsAtUtc: new Date(periodEnd).toISOString(), timezoneLabel: 'UTC', expectedHourlySlotCount: expected, observedHourlySlotCount: observed, missingHourlySlotCount: missing, coverageStatus: missing ? 'partial' : 'complete', temperatureMinF: observations.length ? Math.min(...observations.map(item => item.temperatureF)) : null, temperatureMaxF: observations.length ? Math.max(...observations.map(item => item.temperatureF)) : null, precipitationProbabilityMax: observations.length ? Math.max(...observations.map(item => item.precipitationProbability)) : null, sustainedWindMinMph: observations.length ? Math.min(...observations.map(item => item.windSpeedMph)) : null, sustainedWindMaxMph: observations.length ? Math.max(...observations.map(item => item.windSpeedMph)) : null, ...(gusts.length ? { windGustMaxMph: Math.max(...gusts) } : {}), significantCondition: conditions[0]?.condition ?? null, provider: record.provider.name, retrievedAtUtc: record.retrievedAtUtc, freshness: 'live', limitations: [...record.limitations, ...(missing ? [`${missing} hourly slot(s) are missing; no interpolation was performed.`] : [])], hourlyObservationIndexes: indexes, hourlyObservationTimestampsUtc: observations.map(item => item.startsAtUtc) });
  }
  return periods;
}

export function validateMissionForecastRecord(value: unknown): value is MissionForecastRecord {
  if (!isRecord(value) || value.schemaVersion !== MISSION_FORECAST_SCHEMA_VERSION || typeof value.briefId !== 'string' || !isRecord(value.activation) || typeof value.activation.program !== 'string' || typeof value.activation.reference !== 'string' || !isRecord(value.plannedSite) || !finite(value.plannedSite.latitude) || value.plannedSite.latitude < -90 || value.plannedSite.latitude > 90 || !finite(value.plannedSite.longitude) || value.plannedSite.longitude < -180 || value.plannedSite.longitude > 180 || (value.plannedSite.gridSquare !== null && typeof value.plannedSite.gridSquare !== 'string') || typeof value.plannedSite.provenance !== 'string' || !isRecord(value.missionWindow) || !timestamp(value.missionWindow.start) || !timestamp(value.missionWindow.end) || Date.parse(value.missionWindow.end) < Date.parse(value.missionWindow.start) || !isRecord(value.provider) || value.provider.id !== MISSION_FORECAST_PROVIDER_ID || value.provider.name !== 'Open-Meteo' || value.provider.timezone !== 'UTC' || !timestamp(value.retrievedAtUtc) || !Array.isArray(value.hourly) || !Array.isArray(value.periods) || !isRecord(value.presentation) || !['hourly', 'aggregated'].includes(value.presentation.mode) || value.presentation.hourlyThresholdHours !== MISSION_FORECAST_HOURLY_PRESENTATION_MAX_HOURS || value.presentation.boundaryStrategy !== 'utc_fixed_six_hour_periods' || value.status !== 'live' || !['complete', 'partial', 'outside_provider_horizon'].includes(value.coverageStatus) || typeof value.sourceUrl !== 'string' || !Array.isArray(value.limitations) || !value.limitations.every(item => typeof item === 'string') || !Array.isArray(value.diagnostics) || !value.diagnostics.every(item => typeof item === 'string') || !timestamp(value.updatedAtUtc)) return false;
  return value.hourly.every(hour => isRecord(hour) && timestamp(hour.startsAtUtc) && timestamp(hour.endsAtUtc) && hour.missionApplicable === true && finite(hour.temperatureF) && finite(hour.precipitationProbability) && hour.precipitationProbability >= 0 && hour.precipitationProbability <= 100 && finite(hour.windSpeedMph) && hour.windSpeedMph >= 0 && finite(hour.windDirectionDegrees) && hour.windDirectionDegrees >= 0 && hour.windDirectionDegrees < 360 && typeof hour.windDirection === 'string' && finite(hour.weatherCode) && hour.weatherCode >= 0 && typeof hour.condition === 'string' && (hour.windGustMph === undefined || (finite(hour.windGustMph) && hour.windGustMph >= 0))) && value.periods.every(hour => isRecord(hour) && timestamp(hour.startsAtUtc) && timestamp(hour.endsAtUtc) && hour.missionApplicable === true && finite(hour.temperatureF) && finite(hour.precipitationProbability) && finite(hour.windSpeedMph) && finite(hour.windDirectionDegrees) && typeof hour.windDirection === 'string' && finite(hour.weatherCode) && typeof hour.condition === 'string') && value.operatingPeriods.every(period => isRecord(period) && typeof period.periodId === 'string' && typeof period.label === 'string' && timestamp(period.startsAtUtc) && timestamp(period.endsAtUtc) && period.timezoneLabel === 'UTC' && count(period.expectedHourlySlotCount) && count(period.observedHourlySlotCount) && count(period.missingHourlySlotCount) && period.observedHourlySlotCount <= period.expectedHourlySlotCount && period.missingHourlySlotCount === period.expectedHourlySlotCount - period.observedHourlySlotCount && ['complete', 'partial', 'outside_provider_horizon'].includes(period.coverageStatus) && nullableFinite(period.temperatureMinF) && nullableFinite(period.temperatureMaxF) && nullableFinite(period.precipitationProbabilityMax) && nullableFinite(period.sustainedWindMinMph) && nullableFinite(period.sustainedWindMaxMph) && (period.windGustMaxMph === undefined || (finite(period.windGustMaxMph) && period.windGustMaxMph >= 0)) && (period.significantCondition === null || typeof period.significantCondition === 'string') && period.provider === 'Open-Meteo' && timestamp(period.retrievedAtUtc) && ['live', 'retained', 'stale'].includes(period.freshness) && Array.isArray(period.limitations) && period.limitations.every(item => typeof item === 'string') && Array.isArray(period.hourlyObservationIndexes) && period.hourlyObservationIndexes.every(index => count(index) && index < value.hourly.length) && Array.isArray(period.hourlyObservationTimestampsUtc) && period.hourlyObservationTimestampsUtc.every(item => timestamp(item))) && ['live', 'retained', 'stale'].includes(value.freshness);
}

export function normalizeRetainedMissionForecast(value: unknown): MissionForecastRecord | null {
  if (!isRecord(value)) return null;
  if (value.schemaVersion === MISSION_FORECAST_SCHEMA_VERSION) return validateMissionForecastRecord(value) ? value : null;
  if (value.schemaVersion !== MISSION_FORECAST_PREVIOUS_SCHEMA_VERSION || !validateLegacyRecord(value)) return null;
  const hourly = value.periods.map(period => ({ startsAtUtc: period.startsAtUtc, endsAtUtc: period.endsAtUtc, missionApplicable: true, temperatureF: period.temperatureF, precipitationProbability: period.precipitationProbability, windSpeedMph: period.windSpeedMph, windDirectionDegrees: period.windDirectionDegrees, windDirection: period.windDirection, ...(period.windGustMph === undefined ? {} : { windGustMph: period.windGustMph }), weatherCode: period.weatherCode, condition: period.condition }));
  const base = { schemaVersion: MISSION_FORECAST_SCHEMA_VERSION, briefId: value.briefId, activation: value.activation, plannedSite: value.plannedSite, missionWindow: value.missionWindow, provider: value.provider, retrievedAtUtc: value.retrievedAtUtc, hourly, status: 'live' as const, freshness: 'retained' as const, sourceUrl: value.sourceUrl, limitations: value.limitations, diagnostics: [...value.diagnostics, 'Retained forecast schema-v1 was normalized in memory; no hourly values were fabricated.'], updatedAtUtc: value.updatedAtUtc };
  const start = Date.parse(value.missionWindow.start); const end = Date.parse(value.missionWindow.end); const expectedHours = Math.ceil((end - start) / 3_600_000); const observedHours = hourly.length;
  return { ...base, periods: hourly, operatingPeriods: deriveMissionForecastPeriods(base), presentation: { mode: (end - start) / 3_600_000 <= MISSION_FORECAST_HOURLY_PRESENTATION_MAX_HOURS ? 'hourly' : 'aggregated', hourlyThresholdHours: MISSION_FORECAST_HOURLY_PRESENTATION_MAX_HOURS, boundaryStrategy: 'utc_fixed_six_hour_periods' }, coverageStatus: observedHours >= expectedHours ? 'complete' : 'partial' };
}

function validateLegacyRecord(value: Record<string, any>): boolean { return typeof value.briefId === 'string' && isRecord(value.activation) && typeof value.activation.program === 'string' && typeof value.activation.reference === 'string' && isRecord(value.plannedSite) && finite(value.plannedSite.latitude) && finite(value.plannedSite.longitude) && isRecord(value.missionWindow) && timestamp(value.missionWindow.start) && timestamp(value.missionWindow.end) && isRecord(value.provider) && value.provider.id === MISSION_FORECAST_PROVIDER_ID && value.provider.name === 'Open-Meteo' && value.provider.timezone === 'UTC' && timestamp(value.retrievedAtUtc) && Array.isArray(value.periods) && value.periods.every((period: unknown) => isRecord(period) && timestamp(period.startsAtUtc) && timestamp(period.endsAtUtc) && finite(period.temperatureF) && finite(period.precipitationProbability) && finite(period.windSpeedMph) && finite(period.windDirectionDegrees) && typeof period.windDirection === 'string' && finite(period.weatherCode) && typeof period.condition === 'string' && (period.windGustMph === undefined || finite(period.windGustMph))) && value.status === 'live' && typeof value.sourceUrl === 'string' && Array.isArray(value.limitations) && Array.isArray(value.diagnostics) && timestamp(value.updatedAtUtc); }
function unusable(): MissionForecastRetrieval { return { status: 'provider_unusable', record: null, message: 'The terrestrial forecast provider returned unusable data.' }; }
function finite(value: unknown): value is number { return typeof value === 'number' && Number.isFinite(value); }
function timestamp(value: unknown): value is string { return typeof value === 'string' && Number.isFinite(Date.parse(value)); }
function parseProviderTimestamp(value: string): number { return Date.parse(/[zZ]|[+-]\d\d:\d\d$/.test(value) ? value : `${value}Z`); }
function isRecord(value: unknown): value is Record<string, any> { return typeof value === 'object' && value !== null && !Array.isArray(value); }
function directionLabel(degrees: number): string { return ['N', 'NE', 'E', 'SE', 'S', 'SW', 'W', 'NW'][Math.round(degrees / 45) % 8]; }
function conditionLabel(code: number): string { return code >= 95 ? 'Thunderstorm' : code >= 51 ? 'Precipitation/Rain' : code > 1 ? 'Cloudy' : 'Clear Sky'; }
function conditionSeverity(code: number): number { return code >= 95 ? 4 : code >= 80 ? 3 : code >= 51 ? 2 : code > 1 ? 1 : 0; }
function utcPeriodLabel(timestampMs: number): string { const hour = new Date(timestampMs).getUTCHours(); return hour < 6 ? 'Overnight (UTC)' : hour < 12 ? 'Morning (UTC)' : hour < 18 ? 'Afternoon (UTC)' : 'Evening (UTC)'; }
function nullableFinite(value: unknown): boolean { return value === null || finite(value); }
function count(value: unknown): value is number { return typeof value === 'number' && Number.isSafeInteger(value) && value >= 0; }
function fetchWithTimeout(fetcher: typeof fetch, timeoutMs: number): typeof fetch { return async (input, init) => { const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), timeoutMs); try { return await fetcher(input, { ...init, signal: controller.signal }); } finally { clearTimeout(timer); } }; }