import express, { type Router } from 'express';
import type { SmartDeployBriefStore } from './smartDeployBriefStore';
import { refreshRetainedSpaceWeather } from './spaceWeatherSnapshot';
import type { SpaceWeatherService } from './spaceWeather';
import type { SpaceWeatherSnapshotStore } from './spaceWeatherSnapshotStore';

export function createSpaceWeatherSnapshotRouter(options: { readonly briefStore: SmartDeployBriefStore; readonly store: SpaceWeatherSnapshotStore; readonly service: SpaceWeatherService; readonly now?: () => Date; }): Router {
  const router = express.Router();
  router.get('/api/space-weather/brief/:briefId', (request, response) => { const brief = options.briefStore.get(request.params.briefId); if (brief.status === 'notFound') return response.status(404).json({ code: 'brief_not_found', message: 'The SmartDeploy brief was not found.' }); const result = options.store.getByBriefId(request.params.briefId); return response.json({ kind: 'space_weather_snapshot', status: result.status === 'found' ? 'retained' : 'not_requested', refresh: 'not_requested', retainedStatus: result.status === 'found' ? 'prior_valid_snapshot' : 'none', record: result.status === 'found' ? result.record : null, diagnostics: result.diagnostics }); });
  router.post('/api/space-weather/brief/:briefId/refresh', async (request, response) => { const brief = options.briefStore.get(request.params.briefId); if (brief.status === 'notFound') return response.status(404).json({ code: 'brief_not_found', message: 'The SmartDeploy brief was not found.' }); if (brief.brief.schemaVersion !== 2) return response.status(409).json({ code: 'unsupported_brief_schema', message: 'This retained SmartDeploy brief schema is unsupported for space weather.' }); const prior = options.store.getByBriefId(request.params.briefId); try { const record = await refreshRetainedSpaceWeather(brief.brief, { service: options.service, now: options.now }); options.store.save(record); return response.json({ kind: 'space_weather_snapshot', status: 'live', refresh: 'succeeded', retainedStatus: prior.status === 'found' ? 'prior_valid_snapshot' : 'none', record, diagnostics: prior.diagnostics }); } catch { return response.status(503).json({ kind: 'space_weather_snapshot', status: 'retained_refresh_failed', refresh: 'failed', retainedStatus: prior.status === 'found' ? 'prior_valid_snapshot' : 'none', record: prior.status === 'found' ? prior.record : null, code: 'retained_refresh_failed', message: 'Space-weather refresh failed; prior retained evidence was preserved.' }); } });
  return router;
}