import http from 'node:http';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import express from 'express';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { createMissionForecastRouter } from '../missionForecastApi';
import { MissionForecastStore } from '../missionForecastStore';

const directories: string[] = [];
afterEach(() => { for (const directory of directories.splice(0)) fs.rmSync(directory, { recursive: true, force: true }); });
function brief(schemaVersion = 2, id = 'brief-1'): any { return { schemaVersion, briefId: id, activation: { program: 'POTA', reference: 'US-1' }, plannedOperatingSite: { location: { coordinates: { lat: 40, lon: -75 }, gridSquare: 'FM19', provenance: 'manual' }, source: 'operator_planned_override', description: 'planned' }, missionWindow: { start: '2026-08-19T12:00:00.000Z', midpoint: '2026-08-19T13:00:00.000Z', end: '2026-08-19T14:00:00.000Z' } }; }
function forecast(briefId = 'brief-1'): any { return { schemaVersion: 1, briefId, activation: { program: 'POTA', reference: 'US-1' }, plannedSite: { latitude: 40, longitude: -75, gridSquare: 'FM19', provenance: 'manual' }, missionWindow: { start: '2026-08-19T12:00:00.000Z', end: '2026-08-19T14:00:00.000Z' }, provider: { id: 'open-meteo-mission-forecast', name: 'Open-Meteo', timezone: 'UTC' }, retrievedAtUtc: '2026-08-19T11:00:00.000Z', periods: [{ startsAtUtc: '2026-08-19T12:00:00.000Z', endsAtUtc: '2026-08-19T13:00:00.000Z', temperatureF: 0, precipitationProbability: 0, windSpeedMph: 0, windDirectionDegrees: 0, windDirection: 'N', weatherCode: 0, condition: 'Clear Sky' }], status: 'live', sourceUrl: 'https://api.open-meteo.com/v1/forecast', limitations: [], diagnostics: [], updatedAtUtc: '2026-08-19T11:00:00.000Z' }; }
function responseBody() { return new Response(JSON.stringify({ hourly: { time: ['2026-08-19T12:00', '2026-08-19T14:00'], temperature_2m: [10, 99], precipitation_probability: [0, 100], wind_speed_10m: [0, 20], wind_direction_10m: [0, 180], wind_gusts_10m: [0, 25], weather_code: [0, 61] } }), { status: 200 }); }
async function withApi(config: { readonly brief?: any; readonly store?: MissionForecastStore; readonly fetcher?: typeof fetch }, callback: (url: string, fetcher: ReturnType<typeof vi.fn>, store: MissionForecastStore) => Promise<void>) {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), 'fieldops-forecast-api-')); directories.push(directory);
  const store = config.store ?? new MissionForecastStore(path.join(directory, 'mission-forecasts.json'));
  const fetcher = (config.fetcher ?? vi.fn(async () => responseBody())) as ReturnType<typeof vi.fn>;
  const app = express(); app.use(createMissionForecastRouter({ store, briefStore: { get: vi.fn((id: string) => config.brief && config.brief.briefId === id ? { status: 'found', brief: config.brief, diagnostics: [] } : { status: 'notFound', diagnostics: [] }) } as any, fetcher: fetcher as typeof fetch, now: () => new Date('2026-08-19T11:00:00.000Z') }));
  const server = http.createServer(app); await new Promise<void>(resolve => server.listen(0, resolve)); const address = server.address(); const url = `http://127.0.0.1:${typeof address === 'object' && address ? address.port : 0}`;
  try { await callback(url, fetcher, store); } finally { await new Promise<void>(resolve => server.close(() => resolve())); }
}
async function request(url: string, method = 'GET') { const response = await fetch(url, { method }); return { status: response.status, body: await response.json() as any }; }

describe('mission forecast API', () => {
  it('local GET never calls the provider and reports no retained record', async () => { await withApi({ brief: brief() }, async (url, fetcher) => { const result = await request(`${url}/api/mission-forecast/brief/brief-1`); expect(result.status).toBe(200); expect(result.body.status).toBe('not_requested'); expect(fetcher).not.toHaveBeenCalled(); }); });
  it('returns safe brief and legacy errors without provider access', async () => { await withApi({ brief: brief(1) }, async (url, fetcher) => { const legacy = await request(`${url}/api/mission-forecast/brief/brief-1`); const missing = await request(`${url}/api/mission-forecast/brief/missing`); expect(legacy.status).toBe(409); expect(legacy.body.code).toBe('unsupported_brief_schema'); expect(missing.status).toBe(404); expect(missing.body.code).toBe('brief_not_found'); expect(JSON.stringify(missing.body)).not.toContain('mission-forecasts.json'); expect(fetcher).not.toHaveBeenCalled(); }); });
  it('refreshes only after retained brief resolution and persists complete schema-v2 evidence without the exact-end row', async () => { await withApi({ brief: brief() }, async (url, fetcher, store) => { const result = await request(`${url}/api/mission-forecast/brief/brief-1/refresh`, 'POST'); expect(result.status).toBe(200); expect(result.body.record).toMatchObject({ schemaVersion: 2, plannedSite: { latitude: 40, longitude: -75, gridSquare: 'FM19' }, freshness: 'live' }); expect(result.body.record.hourly).toHaveLength(1); expect(result.body.record.hourly[0].missionApplicable).toBe(true); expect(result.body.record.operatingPeriods[0].freshness).toBe('live'); expect(String(fetcher.mock.calls[0][0])).toContain('latitude=40&longitude=-75'); expect(store.getByBriefId('brief-1')).toMatchObject({ status: 'found', record: { schemaVersion: 2, hourly: [{ startsAtUtc: '2026-08-19T12:00:00.000Z' }], operatingPeriods: [{ freshness: 'retained' }] } }); }); });
  it('returns prior evidence after an unavailable refresh without replacing it', async () => { const store = new MissionForecastStore(path.join(fs.mkdtempSync(path.join(os.tmpdir(), 'fieldops-forecast-prior-')), 'mission-forecasts.json')); store.save(forecast()); directories.push(path.dirname((store as any).filePath)); await withApi({ brief: brief(), store, fetcher: vi.fn(async () => new Response('', { status: 503 })) }, async (url) => { const result = await request(`${url}/api/mission-forecast/brief/brief-1/refresh`, 'POST'); expect(result.status).toBe(503); expect(result.body.status).toBe('retained_refresh_failed'); expect(result.body.record.briefId).toBe('brief-1'); expect(store.getByBriefId('brief-1').status).toBe('found'); }); });
  it('does not call the provider for a missing brief during refresh', async () => { await withApi({}, async (url, fetcher) => { const result = await request(`${url}/api/mission-forecast/brief/missing/refresh`, 'POST'); expect(result.status).toBe(404); expect(fetcher).not.toHaveBeenCalled(); }); });
  it('does not call the provider for legacy or invalid planned-site briefs', async () => { await withApi({ brief: brief(1) }, async (url, fetcher) => { const legacy = await request(`${url}/api/mission-forecast/brief/brief-1/refresh`, 'POST'); expect(legacy.status).toBe(409); expect(fetcher).not.toHaveBeenCalled(); }); await withApi({ brief: { ...brief(), plannedOperatingSite: { ...brief().plannedOperatingSite, location: { coordinates: null, provenance: 'unavailable' } } } }, async (url, fetcher) => { const invalid = await request(`${url}/api/mission-forecast/brief/brief-1/refresh`, 'POST'); expect(invalid.status).toBe(422); expect(invalid.body.code).toBe('planned_coordinates_invalid'); expect(fetcher).not.toHaveBeenCalled(); }); });
  it('never consults current-device coordinates during refresh', async () => { await withApi({ brief: { ...brief(), currentDeviceLocation: { coordinates: { lat: 1, lon: 2 } } } }, async (url, fetcher) => { await request(`${url}/api/mission-forecast/brief/brief-1/refresh`, 'POST'); expect(String(fetcher.mock.calls[0][0])).toContain('latitude=40&longitude=-75'); expect(String(fetcher.mock.calls[0][0])).not.toContain('latitude=1'); }); });
  it('returns safe diagnostics for malformed retained evidence', async () => { const directory = fs.mkdtempSync(path.join(os.tmpdir(), 'fieldops-forecast-api-invalid-')); directories.push(directory); const filePath = path.join(directory, 'mission-forecasts.json'); fs.writeFileSync(filePath, JSON.stringify({ storeVersion: 1, records: [{ briefId: 'brief-1', record: { invalid: true } }] })); await withApi({ brief: brief(), store: new MissionForecastStore(filePath) }, async (url, fetcher) => { const result = await request(`${url}/api/mission-forecast/brief/brief-1`); expect(result.status).toBe(200); expect(result.body.status).toBe('not_requested'); expect(result.body.diagnostics[0].code).toBe('invalid_record'); expect(JSON.stringify(result.body)).not.toContain(filePath); expect(fetcher).not.toHaveBeenCalled(); }); });
});