import React, { useEffect, useState } from 'react';
import type { SmartDeployBriefV2 } from '../../server/smartDeployBrief';
import type { Activation } from '../../server/activation';
import { openActivationFromBrief, updateActivationStatus } from '../activationApi';

export const ActivationFoundationPanel: React.FC<{ brief: SmartDeployBriefV2 }> = ({ brief }) => {
  const [activation, setActivation] = useState<Activation | null>(null);
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState<string | null>(null);
  useEffect(() => { setActivation(null); setMessage(null); }, [brief.briefId]);
  const open = async () => { setBusy(true); setMessage(null); const result = await openActivationFromBrief(brief.briefId); if (result.kind === 'activation') setActivation(result.activation); else setMessage(result.message); setBusy(false); };
  const changeStatus = async (status: Activation['status']) => { if (!activation) return; setBusy(true); setMessage(null); const result = await updateActivationStatus(activation.activationId, status); if (result.kind === 'activation') setActivation(result.activation); else setMessage(result.message); setBusy(false); };
  const location = activation?.plannedLocation;
  return <section className="rounded-xl border border-cyan-700/70 bg-cyan-950/20 p-3 space-y-3" aria-label="Activation">
    <div className="flex flex-wrap items-center justify-between gap-2"><div><h3 className="font-black text-sm uppercase text-cyan-300">ACTIVATION</h3><p className="text-[10px] text-slate-400">Durable field-operation context for this retained plan</p></div>{activation ? <span className="rounded border border-cyan-600 px-2 py-1 text-[10px] font-black uppercase text-cyan-200">{activation.status}</span> : <button type="button" onClick={() => void open()} disabled={busy} className="min-h-11 rounded border border-cyan-600 px-3 py-2 text-[10px] font-bold text-cyan-200">{busy ? 'OPENING...' : 'OPEN ACTIVATION'}</button>}</div>
    {activation && <><div className="grid grid-cols-1 sm:grid-cols-2 gap-2"><Detail label="IDENTITY" value={`${activation.type}${activation.reference ? ` / ${activation.reference}` : ''}${activation.title ? ` - ${activation.title}` : ''}`} /><Detail label="PLANNED LOCATION" value={location ? `${location.gridSquare || 'Grid unavailable'} / ${location.latitude.toFixed(5)}, ${location.longitude.toFixed(5)}` : 'Unknown'} /><Detail label="MISSION WINDOW" value={activation.missionWindow ? `${formatUtc(activation.missionWindow.start)} to ${formatUtc(activation.missionWindow.end)}` : 'Unknown'} /><Detail label="RECORD" value={`${activation.activationId} / brief ${activation.briefId || 'not associated'}`} /></div><div className="flex flex-wrap items-center gap-2">{activation.status === 'planned' && <button type="button" disabled={busy} onClick={() => void changeStatus('active')} className="min-h-11 rounded border border-emerald-700 px-3 py-2 text-[10px] font-bold text-emerald-200">MARK ACTIVE</button>}{activation.status === 'active' && <button type="button" disabled={busy} onClick={() => void changeStatus('completed')} className="min-h-11 rounded border border-amber-700 px-3 py-2 text-[10px] font-bold text-amber-200">MARK COMPLETED</button>}{activation.notesCollectionId && <a href="#activation-notes" className="min-h-11 rounded border border-cyan-700 px-3 py-3 text-[10px] font-bold text-cyan-200">OPEN ASSOCIATED NOTES</a>}</div></>}
    {message && <p role="alert" className="text-[11px] text-amber-200">{message}</p>}
  </section>;
};
const Detail: React.FC<{ label: string; value: string }> = ({ label, value }) => <div className="rounded border border-slate-800 bg-slate-900/70 p-2"><span className="block text-[9px] uppercase text-slate-500">{label}</span><span className="block mt-0.5 break-words text-[11px] text-slate-200">{value}</span></div>;
function formatUtc(value: string): string { const date = new Date(value); return Number.isNaN(date.getTime()) ? 'Unknown time' : date.toISOString().replace('T', ' ').replace('.000Z', ' UTC'); }