import React, { useEffect, useState } from 'react';
import type { ActivationReview } from '../../server/activationReview';
import type { Activation } from '../../server/activation';
import { getActivationReview } from '../activationReviewApi';
import { MySignalPanel } from './MySignalPanel';
import { LayeredPropagationPicture } from './LayeredPropagationPicture';

export const ActivationReviewPanel: React.FC<{ activation: Activation }> = ({ activation }) => {
  const [review, setReview] = useState<ActivationReview | null>(null);
  const [message, setMessage] = useState<string | null>(null);
  useEffect(() => { setReview(null); setMessage(null); const controller = new AbortController(); void getActivationReview(activation.activationId, controller.signal).then(setReview).catch(error => { if (error?.name !== 'AbortError') setMessage(error instanceof Error ? error.message : 'Activation Review could not be loaded.'); }); return () => controller.abort(); }, [activation.activationId]);
  if (message) return <section className="rounded-xl border border-red-700/70 bg-red-950/20 p-3" aria-label="Activation Review"><p role="alert" className="text-[11px] text-red-200">{message}</p></section>;
  if (!review) return <section className="rounded-xl border border-cyan-700/70 bg-cyan-950/20 p-3" aria-label="Activation Review"><p role="status" className="text-[11px] text-slate-400">Loading Activation Review...</p></section>;
  if (activation.status !== 'completed') return <section className="rounded-xl border border-amber-700/70 bg-amber-950/20 p-3 space-y-2" aria-label="Activation Review"><h3 className="font-black text-sm uppercase text-amber-300">ACTIVATION REVIEW</h3><p className="text-[11px] text-slate-200">Review available after activation is completed.</p><details><summary className="cursor-pointer text-[10px] font-black uppercase text-cyan-300">Evidence Details</summary><p className="mt-2 text-[10px] text-slate-400">Current status: {activation.status}. Retained evidence remains available after completion.</p></details></section>;
  const { plan, environment, propagation, results, notes } = review;
  return <section id="activation-review" className="rounded-xl border border-emerald-700/70 bg-emerald-950/20 p-3 space-y-3" aria-label="Activation Review">
    <div className="flex flex-wrap items-start justify-between gap-2"><div><h3 className="font-black text-sm uppercase text-emerald-300">ACTIVATION REVIEW</h3><p className="text-[10px] text-slate-400">Read-only assembly of retained Activation evidence</p></div><span className="rounded border border-emerald-600 px-2 py-1 text-[10px] font-black uppercase text-emerald-200">{activation.status}{activation.status === 'completed' ? '' : ' / PROVISIONAL'}</span></div>
    <ReviewSection title="ACTIVATION"><Detail label="IDENTITY" value={`${activation.type}${activation.reference ? ` / ${activation.reference}` : ''}${activation.title ? ` - ${activation.title}` : ''}`} /><Detail label="STATUS" value={activation.status} /><Detail label="REVIEWED UTC" value={formatUtc(review.reviewedAtUtc)} /></ReviewSection>
    <ReviewSection title="PLAN"><Detail label="SOURCE" value={plan.state === 'retained' ? 'Retained SmartDeploy plan' : 'Unavailable'} /><Detail label="TYPE / REFERENCE" value={`${plan.type} / ${plan.reference || 'Unavailable'}`} /><Detail label="NAME" value={plan.displayName || 'Unavailable'} /><Detail label="SITE / GRID" value={plan.plannedLocation ? `${plan.plannedLocation.latitude.toFixed(5)}, ${plan.plannedLocation.longitude.toFixed(5)} / ${plan.plannedLocation.gridSquare || 'Grid unavailable'}` : 'Unavailable'} /><Detail label="MISSION WINDOW" value={plan.missionWindow ? `${formatUtc(plan.missionWindow.start)} to ${formatUtc(plan.missionWindow.end)}` : 'Unavailable'} /><Detail label="BANDS / MODES" value={`${plan.bands.join(', ') || 'Not explicitly planned'} / ${plan.modes.join(', ') || 'Unavailable'}`} /><Detail label="POWER / STRATEGY" value={`${plan.powerWatts === null ? 'Unavailable' : `${plan.powerWatts} W`} / ${plan.sequence || 'Unavailable'}`} /></ReviewSection>
    <ReviewSection title="ENVIRONMENT"><Evidence label="MISSION FORECAST" state={environment.forecast.state} value={environment.forecast.record ? `${environment.forecast.record.provider?.name || 'Open-Meteo'}; captured ${formatUtc(environment.forecast.record.retrievedAtUtc)}; ${environment.forecast.record.hourly?.length || environment.forecast.record.periods.length} retained hourly evidence row(s); ${environment.forecast.record.operatingPeriods?.length || 0} derived operating period(s)` : 'No retained mission forecast is available.'} /><Evidence label="ALERTS" state={environment.alerts.state} value={environment.alerts.message} /><Evidence label="SPACE WEATHER" state={environment.spaceWeather.state} value={environment.spaceWeather.record ? `${environment.spaceWeather.record.source.name}; captured ${formatUtc(environment.spaceWeather.record.retrievedAtUtc)}; ${environment.spaceWeather.record.interpretation.plainLanguageEffect}` : 'No retained space-weather evidence is available.'} /></ReviewSection>
    <ReviewSection title="PROPAGATION"><Evidence label="MODELED EVIDENCE" state={propagation.state} value={propagation.modeled ? 'Retained SmartDeploy modeled propagation evidence.' : 'No retained propagation evidence is available.'} /><Evidence label="OBSERVED RF" state={propagation.observedRf ? 'retained' : 'unavailable'} value={propagation.observedRf ? 'Retained observed-RF evidence; observational only, not a forecast.' : 'No observed-RF evidence is available.'} /><p className="text-[10px] text-slate-400">{propagation.source}</p></ReviewSection>
    <ReviewSection title="RESULTS"><div className="grid grid-cols-2 sm:grid-cols-4 gap-2"><Detail label="TOTAL QSOs" value={String(results.total)} /><Detail label="IN WINDOW" value={String(results.inWindowTotal)} /><Detail label="OUTSIDE WINDOW" value={String(results.outsideWindowTotal)} /><Detail label="FIRST / LAST UTC" value={`${results.firstQsoUtc ? formatUtc(results.firstQsoUtc) : 'None'} / ${results.lastQsoUtc ? formatUtc(results.lastQsoUtc) : 'None'}`} /></div><Detail label="UNIQUE CALLS / MANUAL / ADIF" value={`${results.uniqueCallsigns} / ${results.manual} / ${results.adifImported}`} /><Detail label="BY BAND" value={formatCounts(results.byBand)} /><Detail label="BY MODE" value={formatCounts(results.byMode)} /><a href="#qso-log" className="inline-block min-h-11 rounded border border-cyan-700 px-3 py-3 text-[10px] font-bold text-cyan-200">OPEN QSO LOGGER</a>{results.qsos.length > 0 && <details><summary className="cursor-pointer text-[10px] font-black uppercase text-cyan-300">QSO detail</summary><div className="mt-2 space-y-1">{results.qsos.map(qso => <p key={qso.qsoId} className="text-[10px] text-slate-300">{formatUtc(qso.qsoDateTimeUtc)} / {qso.callsign} / {qso.band} / {qso.mode} / {qso.source}{results.outsideWindowTotal > 0 && !isInWindow(qso.qsoDateTimeUtc, plan.missionWindow) ? ' / OUTSIDE ACTIVATION WINDOW' : ''}</p>)}</div></details>}</ReviewSection>
    <LayeredPropagationPicture activation={activation} readOnly qsoCount={results.total} evaluatedAtUtc={review.reviewedAtUtc} retained={{ modeled: propagation.modeled, modeledStatus: propagation.state, missionWindow: plan.missionWindow, destinationLabel: plan.displayName ?? undefined, forecast: environment.forecast.record, spaceWeather: environment.spaceWeather.record, generalObserved: propagation.observedRf }} />
    <MySignalPanel activation={activation} readOnly />
      <ReviewSection title="OPERATOR NOTES"><Evidence label="NOTES" state={notes.state} value={notes.collection ? notes.collection.notes.length ? `${notes.collection.notes.length} operator observation(s); updated ${formatUtc(notes.collection.updatedAtUtc)}.` : 'No notes recorded.' : 'No Activation Notes collection is available.'} />{notes.collection && <div className="space-y-1">{notes.collection.notes.map(note => <p key={note.noteId} className="text-[11px] text-slate-200"><time className="block text-cyan-300" dateTime={note.recordedAtUtc}>{formatUtc(note.recordedAtUtc)}</time><span className="block">{note.text}</span></p>)}</div>}<a href="#activation-notes" className="inline-block min-h-11 rounded border border-cyan-700 px-3 py-3 text-[10px] font-bold text-cyan-200">OPEN ACTIVATION NOTES</a></ReviewSection>
    <ReviewSection title="FINDINGS"><ul className="list-disc pl-5 space-y-1 text-[11px] text-amber-100">{review.findings.map(finding => <li key={finding}>{finding}</li>)}</ul><details><summary className="cursor-pointer text-[10px] font-black uppercase text-cyan-300">Evidence details</summary><div className="mt-2 space-y-1 text-[10px] text-slate-400"><p>Retained SmartDeploy brief ID: {plan.briefId || 'Unavailable'}</p>{review.diagnostics.length ? review.diagnostics.map(item => <p key={item}>{item}</p>) : <p>No assembly diagnostics.</p>}<p>Review opening is read-only and does not fetch live providers.</p></div></details></ReviewSection>
  </section>;
};

const ReviewSection: React.FC<React.PropsWithChildren<{ title: string }>> = ({ title, children }) => <section className="rounded-lg border border-slate-700 bg-slate-950/50 p-3 space-y-2"><h4 className="font-black text-[10px] uppercase text-emerald-300">{title}</h4>{children}</section>;
const Detail: React.FC<{ label: string; value: string }> = ({ label, value }) => <div className="rounded border border-slate-800 bg-slate-900/70 p-2"><span className="block text-[9px] uppercase text-slate-500">{label}</span><span className="block mt-0.5 break-words text-[11px] text-slate-200">{value}</span></div>;
const Evidence: React.FC<{ label: string; state: string; value: string }> = ({ label, state, value }) => <div className="border-t border-slate-800 pt-2"><span className="text-[9px] uppercase text-slate-500">{label} / {state}</span><p className="text-[11px] text-slate-200">{value}</p></div>;
function formatCounts(values: Readonly<Record<string, number>>): string { const entries = Object.entries(values); return entries.length ? entries.map(([key, value]) => `${key}: ${value}`).join(' / ') : 'None'; }
function formatUtc(value: string): string { const date = new Date(value); return Number.isNaN(date.getTime()) ? 'Unknown time' : date.toISOString().replace('T', ' ').replace('.000Z', ' UTC'); }
function isInWindow(value: string, window: { start: string; end: string } | null): boolean { if (!window) return true; const timestamp = Date.parse(value); return Number.isFinite(timestamp) && timestamp >= Date.parse(window.start) && timestamp <= Date.parse(window.end); }
