import React, { useEffect, useState } from 'react';
import { ArchiveRestore, PackageOpen, Pencil, Plus, Trash2 } from 'lucide-react';
import { EQUIPMENT_KINDS, type EquipmentKind, type EquipmentRecord, type LoadoutRecord } from '../equipment/domain';
import { fetchEquipmentWorkspace, saveEquipment, saveLoadout, transitionEquipment, transitionLoadout, type EquipmentDraft, type LoadoutDraft } from '../equipment/api';

const emptyEquipment = (): EquipmentDraft => ({ kind: 'radio', label: '', facts: [], limitations: [] });
const emptyLoadout = (): LoadoutDraft => ({ name: '', items: [], limitations: [] });
const lines = (value: string) => value.split('\n').map(item => item.trim()).filter(Boolean);
interface SpecificationOption { readonly key: string; readonly label: string; readonly unit?: string; readonly kinds: readonly EquipmentKind[]; readonly example: string; }
const SPECIFICATIONS: readonly SpecificationOption[] = [
  { key: 'max_output_power_watts', label: 'Maximum output power', unit: 'W', kinds: ['radio', 'amplifier'], example: '10' },
  { key: 'supported_bands', label: 'Supported amateur bands', kinds: ['radio', 'amplifier', 'antenna', 'tuner'], example: '40 m, 20 m, 10 m' },
  { key: 'battery_capacity_amp_hours', label: 'Battery capacity', unit: 'Ah', kinds: ['battery'], example: '20' },
  { key: 'nominal_voltage_volts', label: 'Nominal voltage', unit: 'V', kinds: ['battery', 'power_system'], example: '12.8' },
  { key: 'usable_energy_watt_hours', label: 'Usable energy', unit: 'Wh', kinds: ['battery', 'power_system'], example: '256' },
  { key: 'max_output_watts', label: 'Maximum power output', unit: 'W', kinds: ['power_system'], example: '1000' },
  { key: 'length_meters', label: 'Length', unit: 'm', kinds: ['antenna', 'cable_adapter'], example: '20.4' },
  { key: 'connector_type', label: 'Connector type', kinds: ['antenna', 'tuner', 'interface', 'cable_adapter'], example: 'BNC' },
  { key: 'weight_kilograms', label: 'Weight', unit: 'kg', kinds: EQUIPMENT_KINDS, example: '1.1' },
];
const specificationLabel = (key: string) => SPECIFICATIONS.find(item => item.key === key)?.label ?? key.replaceAll('_', ' ');

export const EquipmentWorkspace: React.FC = () => {
  const [equipment, setEquipment] = useState<readonly EquipmentRecord[]>([]);
  const [loadouts, setLoadouts] = useState<readonly LoadoutRecord[]>([]);
  const [mode, setMode] = useState<'inventory' | 'loadouts'>('inventory');
  const [equipmentDraft, setEquipmentDraft] = useState<EquipmentDraft>(emptyEquipment);
  const [loadoutDraft, setLoadoutDraft] = useState<LoadoutDraft>(emptyLoadout);
  const [editingEquipmentId, setEditingEquipmentId] = useState<string>();
  const [editingLoadoutId, setEditingLoadoutId] = useState<string>();
  const [factKey, setFactKey] = useState(''); const [factValue, setFactValue] = useState('');
  const [selectedEquipmentId, setSelectedEquipmentId] = useState(''); const [selectedRole, setSelectedRole] = useState(''); const [selectedQuantity, setSelectedQuantity] = useState(1);
  const [message, setMessage] = useState('Loading local equipment records…');
  const reload = async () => { try { const data = await fetchEquipmentWorkspace(); setEquipment(data.equipment); setLoadouts(data.loadouts); setMessage(data.equipment.length || data.loadouts.length ? '' : 'No equipment or loadouts have been entered.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Equipment records are unavailable.'); } };
  useEffect(() => { void reload(); }, []);

  const submitEquipment = async () => { try { await saveEquipment(equipmentDraft, editingEquipmentId); setEquipmentDraft(emptyEquipment()); setEditingEquipmentId(undefined); setMessage('Equipment saved.'); await reload(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Equipment could not be saved.'); } };
  const submitLoadout = async () => { try { await saveLoadout(loadoutDraft, editingLoadoutId); setLoadoutDraft(emptyLoadout()); setEditingLoadoutId(undefined); setMessage('Loadout saved.'); await reload(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Loadout could not be saved.'); } };
  const availableSpecifications = SPECIFICATIONS.filter(item => item.kinds.includes(equipmentDraft.kind));
  const selectedSpecification = availableSpecifications.find(item => item.key === factKey);
  const addFact = () => { if (!selectedSpecification || !factValue.trim()) return; const numeric = Number(factValue); setEquipmentDraft({ ...equipmentDraft, facts: [...equipmentDraft.facts.filter(item => item.key !== selectedSpecification.key), { key: selectedSpecification.key, value: Number.isFinite(numeric) && factValue.trim() !== '' ? numeric : factValue.trim(), ...(selectedSpecification.unit ? { unit: selectedSpecification.unit } : {}), source: 'operator_entered' }] }); setFactKey(''); setFactValue(''); };
  const addLoadoutItem = () => { if (!selectedEquipmentId || !selectedRole.trim()) return; setLoadoutDraft({ ...loadoutDraft, items: [...loadoutDraft.items, { equipmentId: selectedEquipmentId, role: selectedRole.trim(), quantity: selectedQuantity }] }); setSelectedEquipmentId(''); setSelectedRole(''); setSelectedQuantity(1); };
  const editEquipment = (item: EquipmentRecord) => { setEditingEquipmentId(item.equipmentId); setEquipmentDraft({ kind: item.kind, label: item.label, manufacturer: item.manufacturer, model: item.model, notes: item.notes, facts: item.facts.map(fact => ({ ...fact, source: 'operator_entered' })), limitations: item.limitations }); };
  const editLoadout = (item: LoadoutRecord) => { setEditingLoadoutId(item.loadoutId); setLoadoutDraft({ name: item.name, description: item.description, items: item.items, limitations: item.limitations }); };

  return <div id="field-tools-equipment" className="space-y-4">
    <div className="p-4 rounded-xl border border-cyan-700/70 bg-cyan-950/20 space-y-4">
      <div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-black text-sm text-cyan-300 flex items-center gap-2"><PackageOpen className="w-4 h-4" /> EQUIPMENT & LOADOUTS</h3><p className="text-[11px] text-slate-400 mt-1">Locally retained operator facts and reusable packing plans.</p></div><span className="px-2 py-1 rounded border border-emerald-500/40 bg-emerald-500/10 text-[10px] font-black text-emerald-300">OFFLINE / LOCAL</span></div>
      <div role="tablist" className="flex gap-2"><button role="tab" aria-selected={mode === 'inventory'} onClick={() => setMode('inventory')} className="fo-control min-h-11 px-4 rounded border font-black">INVENTORY ({equipment.filter(item => item.state === 'active').length})</button><button role="tab" aria-selected={mode === 'loadouts'} onClick={() => setMode('loadouts')} className="fo-control min-h-11 px-4 rounded border font-black">LOADOUTS ({loadouts.filter(item => item.state === 'active').length})</button></div>
      {message && <div role="status" className="p-3 rounded border border-amber-700/60 bg-amber-950/20 text-amber-200">{message}</div>}

      {mode === 'inventory' ? <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
        <section className="p-3 rounded-lg border border-slate-700 bg-slate-950/60 space-y-3"><h4 className="font-black text-cyan-200">{editingEquipmentId ? 'EDIT EQUIPMENT' : 'ADD EQUIPMENT'}</h4>
          <label className="block">Equipment type<select aria-label="Equipment type" value={equipmentDraft.kind} onChange={e => { setEquipmentDraft({ ...equipmentDraft, kind: e.target.value as EquipmentKind }); setFactKey(''); setFactValue(''); }} className="mt-1 min-h-11 w-full bg-slate-900 border border-slate-700 rounded px-3">{EQUIPMENT_KINDS.map(kind => <option key={kind} value={kind}>{kind.replace('_', ' ')}</option>)}</select></label>
          <Text label="Equipment label" value={equipmentDraft.label} set={label => setEquipmentDraft({ ...equipmentDraft, label })} /><div className="grid grid-cols-2 gap-2"><Text label="Manufacturer" value={equipmentDraft.manufacturer ?? ''} set={manufacturer => setEquipmentDraft({ ...equipmentDraft, manufacturer })} /><Text label="Model" value={equipmentDraft.model ?? ''} set={model => setEquipmentDraft({ ...equipmentDraft, model })} /></div>
          <div className="rounded-lg border border-slate-700 bg-slate-900/50 p-3 space-y-2"><h5 className="font-black text-cyan-200">OPTIONAL SPECIFICATIONS</h5><p className="text-[11px] text-slate-400">Add only values you know. Leave unknown specifications blank.</p><div className="grid grid-cols-1 sm:grid-cols-2 gap-2"><label className="block">Specification<select aria-label="Specification" value={factKey} onChange={e => { setFactKey(e.target.value); setFactValue(''); }} className="mt-1 min-h-11 w-full bg-slate-900 border border-slate-700 rounded px-3"><option value="">Choose a specification</option>{availableSpecifications.map(item => <option key={item.key} value={item.key}>{item.label}</option>)}</select></label><label className="block">Value{selectedSpecification?.unit ? ` (${selectedSpecification.unit})` : ''}<input aria-label="Specification value" value={factValue} onChange={e => setFactValue(e.target.value)} placeholder={selectedSpecification ? `Example: ${selectedSpecification.example}` : 'Select a specification first'} disabled={!selectedSpecification} className="mt-1 min-h-11 w-full bg-slate-900 border border-slate-700 rounded px-3 disabled:opacity-50" /></label></div><button onClick={addFact} disabled={!selectedSpecification || !factValue.trim()} className="fo-control min-h-11 w-full rounded border disabled:opacity-50"><Plus className="inline w-4 h-4" /> ADD SPECIFICATION</button>{equipmentDraft.facts.map(fact => <div key={fact.key} className="flex items-center justify-between text-[11px] text-slate-300"><span>{specificationLabel(fact.key)}: <strong>{String(fact.value)} {fact.unit ?? ''}</strong></span><button onClick={() => setEquipmentDraft({ ...equipmentDraft, facts: equipmentDraft.facts.filter(item => item.key !== fact.key) })}>REMOVE</button></div>)}</div>
          <Area label="Known limitations or restrictions" help="Examples: Requires an external tuner on 30 m; maximum 20 W digital duty cycle. Enter one item per line." value={equipmentDraft.limitations.join('\n')} set={value => setEquipmentDraft({ ...equipmentDraft, limitations: lines(value) })} /><Area label="Other notes" value={equipmentDraft.notes ?? ''} set={notes => setEquipmentDraft({ ...equipmentDraft, notes })} /><button onClick={submitEquipment} className="min-h-11 w-full rounded bg-cyan-600 text-slate-950 font-black">SAVE EQUIPMENT</button>
        </section><RecordList records={equipment} edit={editEquipment} transition={async (id, restore) => { await transitionEquipment(id, restore); await reload(); }} />
      </div> : <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
        <section className="p-3 rounded-lg border border-slate-700 bg-slate-950/60 space-y-3"><h4 className="font-black text-cyan-200">{editingLoadoutId ? 'EDIT LOADOUT' : 'ADD LOADOUT'}</h4><Text label="Loadout name" value={loadoutDraft.name} set={name => setLoadoutDraft({ ...loadoutDraft, name })} /><Area label="Description" value={loadoutDraft.description ?? ''} set={description => setLoadoutDraft({ ...loadoutDraft, description })} />
          <label className="block">Equipment<select aria-label="Loadout equipment" value={selectedEquipmentId} onChange={e => setSelectedEquipmentId(e.target.value)} className="mt-1 min-h-11 w-full bg-slate-900 border border-slate-700 rounded px-3"><option value="">Select active equipment</option>{equipment.filter(item => item.state === 'active').map(item => <option key={item.equipmentId} value={item.equipmentId}>{item.label}</option>)}</select></label><div className="grid grid-cols-2 gap-2"><Text label="Role" value={selectedRole} set={setSelectedRole} /><label>Quantity<input aria-label="Quantity" type="number" min="1" max="99" value={selectedQuantity} onChange={e => setSelectedQuantity(Number(e.target.value))} className="mt-1 min-h-11 w-full bg-slate-900 border border-slate-700 rounded px-3" /></label></div><button onClick={addLoadoutItem} className="fo-control min-h-11 w-full rounded border"><Plus className="inline w-4 h-4" /> ADD TO LOADOUT</button>{loadoutDraft.items.map((item, index) => <div key={`${item.equipmentId}-${index}`} className="flex justify-between text-[11px] text-slate-300"><span>{equipment.find(candidate => candidate.equipmentId === item.equipmentId)?.label ?? item.equipmentId} · {item.role} × {item.quantity}</span><button aria-label="Remove loadout item" onClick={() => setLoadoutDraft({ ...loadoutDraft, items: loadoutDraft.items.filter((_, i) => i !== index) })}>REMOVE</button></div>)}
          <Area label="Known loadout limitations or restrictions" help="Examples: Amplifier is not included; battery endurance has not been confirmed. Enter one item per line." value={loadoutDraft.limitations.join('\n')} set={value => setLoadoutDraft({ ...loadoutDraft, limitations: lines(value) })} /><button onClick={submitLoadout} className="min-h-11 w-full rounded bg-cyan-600 text-slate-950 font-black">SAVE LOADOUT</button>
        </section><LoadoutList records={loadouts} equipment={equipment} edit={editLoadout} transition={async (id, restore) => { await transitionLoadout(id, restore); await reload(); }} />
      </div>}
      <p className="border-t border-cyan-800/60 pt-3 text-[11px] text-slate-300">Inventory and loadouts are operator records—not proof that equipment is packed, connected, functional, charged, licensed, or suitable.</p>
    </div>
  </div>;
};

const Text = ({ label, value, set }: { label: string; value: string; set: (value: string) => void }) => <label className="block">{label}<input aria-label={label} value={value} onChange={e => set(e.target.value)} className="mt-1 min-h-11 w-full bg-slate-900 border border-slate-700 rounded px-3" /></label>;
const Area = ({ label, value, set, help }: { label: string; value: string; set: (value: string) => void; help?: string }) => <label className="block">{label}{help && <span className="block mt-0.5 text-[10px] font-normal text-slate-400">{help}</span>}<textarea aria-label={label} value={value} onChange={e => set(e.target.value)} className="mt-1 min-h-16 w-full bg-slate-900 border border-slate-700 rounded p-3" /></label>;
const RecordList = ({ records, edit, transition }: { records: readonly EquipmentRecord[]; edit: (item: EquipmentRecord) => void; transition: (id: string, restore: boolean) => Promise<void> }) => <section className="space-y-2">{records.map(item => <article key={item.equipmentId} className={`p-3 rounded-lg border border-slate-700 bg-slate-950/60 ${item.state === 'deleted' ? 'opacity-60' : ''}`}><strong className="text-cyan-200">{item.label}</strong><span className="block text-[10px] text-slate-400">{item.kind} · {item.manufacturer ?? ''} {item.model ?? ''}</span><div className="mt-2 flex gap-2"><button onClick={() => edit(item)} disabled={item.state === 'deleted'} className="fo-control min-h-11 px-3 rounded border"><Pencil className="inline w-4 h-4" /> EDIT</button><button onClick={() => transition(item.equipmentId, item.state === 'deleted')} className="fo-control min-h-11 px-3 rounded border">{item.state === 'deleted' ? <ArchiveRestore className="inline w-4 h-4" /> : <Trash2 className="inline w-4 h-4" />} {item.state === 'deleted' ? 'RESTORE' : 'DELETE'}</button></div></article>)}</section>;
const LoadoutList = ({ records, equipment, edit, transition }: { records: readonly LoadoutRecord[]; equipment: readonly EquipmentRecord[]; edit: (item: LoadoutRecord) => void; transition: (id: string, restore: boolean) => Promise<void> }) => <section className="space-y-2">{records.map(item => <article key={item.loadoutId} className={`p-3 rounded-lg border border-slate-700 bg-slate-950/60 ${item.state === 'deleted' ? 'opacity-60' : ''}`}><strong className="text-cyan-200">{item.name}</strong>{item.items.map(entry => <span key={`${entry.equipmentId}-${entry.role}`} className="block text-[11px] text-slate-400">{equipment.find(candidate => candidate.equipmentId === entry.equipmentId)?.label ?? entry.equipmentId} · {entry.role} × {entry.quantity}</span>)}<div className="mt-2 flex gap-2"><button onClick={() => edit(item)} disabled={item.state === 'deleted'} className="fo-control min-h-11 px-3 rounded border"><Pencil className="inline w-4 h-4" /> EDIT</button><button onClick={() => transition(item.loadoutId, item.state === 'deleted')} className="fo-control min-h-11 px-3 rounded border">{item.state === 'deleted' ? 'RESTORE' : 'DELETE'}</button></div></article>)}</section>;
