import React, { useEffect, useState } from 'react';
import { ArchiveRestore, PackageOpen, Pencil, Plus, Trash2 } from 'lucide-react';
import { EQUIPMENT_KINDS, type EquipmentKind, type EquipmentRecord, type LoadoutRecord } from '../equipment/domain';
import { fetchEquipmentWorkspace, saveEquipment, saveLoadout, transitionEquipment, transitionLoadout, type EquipmentDraft, type LoadoutDraft } from '../equipment/api';

const emptyEquipment = (): EquipmentDraft => ({ kind: 'radio', label: '', facts: [], limitations: [] });
const emptyLoadout = (): LoadoutDraft => ({ name: '', items: [], limitations: [] });
const lines = (value: string) => value.split('\n').map(item => item.trim()).filter(Boolean);

export const EquipmentWorkspace: React.FC = () => {
  const [equipment, setEquipment] = useState<readonly EquipmentRecord[]>([]);
  const [loadouts, setLoadouts] = useState<readonly LoadoutRecord[]>([]);
  const [mode, setMode] = useState<'inventory' | 'loadouts'>('inventory');
  const [equipmentDraft, setEquipmentDraft] = useState<EquipmentDraft>(emptyEquipment);
  const [loadoutDraft, setLoadoutDraft] = useState<LoadoutDraft>(emptyLoadout);
  const [editingEquipmentId, setEditingEquipmentId] = useState<string>();
  const [editingLoadoutId, setEditingLoadoutId] = useState<string>();
  const [factKey, setFactKey] = useState(''); const [factValue, setFactValue] = useState(''); const [factUnit, setFactUnit] = useState('');
  const [selectedEquipmentId, setSelectedEquipmentId] = useState(''); const [selectedRole, setSelectedRole] = useState(''); const [selectedQuantity, setSelectedQuantity] = useState(1);
  const [message, setMessage] = useState('Loading local equipment records…');
  const reload = async () => { try { const data = await fetchEquipmentWorkspace(); setEquipment(data.equipment); setLoadouts(data.loadouts); setMessage(data.equipment.length || data.loadouts.length ? '' : 'No equipment or loadouts have been entered.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Equipment records are unavailable.'); } };
  useEffect(() => { void reload(); }, []);

  const submitEquipment = async () => { try { await saveEquipment(equipmentDraft, editingEquipmentId); setEquipmentDraft(emptyEquipment()); setEditingEquipmentId(undefined); setMessage('Equipment saved.'); await reload(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Equipment could not be saved.'); } };
  const submitLoadout = async () => { try { await saveLoadout(loadoutDraft, editingLoadoutId); setLoadoutDraft(emptyLoadout()); setEditingLoadoutId(undefined); setMessage('Loadout saved.'); await reload(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Loadout could not be saved.'); } };
  const addFact = () => { if (!factKey.trim() || !factValue.trim()) return; const numeric = Number(factValue); setEquipmentDraft({ ...equipmentDraft, facts: [...equipmentDraft.facts.filter(item => item.key !== factKey.trim().toLowerCase()), { key: factKey.trim().toLowerCase(), value: Number.isFinite(numeric) && factValue.trim() !== '' ? numeric : factValue.trim(), ...(factUnit.trim() ? { unit: factUnit.trim() } : {}), source: 'operator_entered' }] }); setFactKey(''); setFactValue(''); setFactUnit(''); };
  const addLoadoutItem = () => { if (!selectedEquipmentId || !selectedRole.trim()) return; setLoadoutDraft({ ...loadoutDraft, items: [...loadoutDraft.items, { equipmentId: selectedEquipmentId, role: selectedRole.trim(), quantity: selectedQuantity }] }); setSelectedEquipmentId(''); setSelectedRole(''); setSelectedQuantity(1); };
  const editEquipment = (item: EquipmentRecord) => { setEditingEquipmentId(item.equipmentId); setEquipmentDraft({ kind: item.kind, label: item.label, manufacturer: item.manufacturer, model: item.model, notes: item.notes, facts: item.facts.map(fact => ({ ...fact, source: 'operator_entered' })), limitations: item.limitations }); };
  const editLoadout = (item: LoadoutRecord) => { setEditingLoadoutId(item.loadoutId); setLoadoutDraft({ name: item.name, description: item.description, items: item.items, limitations: item.limitations }); };

  return <div id="field-tools-equipment" className="space-y-4">
    <div className="p-4 rounded-xl border border-cyan-700/70 bg-cyan-950/20 space-y-4">
      <div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-black text-sm text-cyan-300 flex items-center gap-2"><PackageOpen className="w-4 h-4" /> EQUIPMENT & LOADOUTS</h3><p className="text-[11px] text-slate-400 mt-1">Locally retained operator facts and reusable packing plans.</p></div><span className="px-2 py-1 rounded border border-emerald-500/40 bg-emerald-500/10 text-[10px] font-black text-emerald-300">OFFLINE / LOCAL</span></div>
      <div role="tablist" className="flex gap-2"><button role="tab" aria-selected={mode === 'inventory'} onClick={() => setMode('inventory')} className="fo-control min-h-11 px-4 rounded border font-black">INVENTORY ({equipment.filter(item => item.state === 'active').length})</button><button role="tab" aria-selected={mode === 'loadouts'} onClick={() => setMode('loadouts')} className="fo-control min-h-11 px-4 rounded border font-black">LOADOUTS ({loadouts.filter(item => item.state === 'active').length})</button></div>
      {message && <div role="status" className="p-3 rounded border border-amber-700/60 bg-amber-950/20 text-amber-200">{message}</div>}

      {mode === 'inventory' ? <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
        <section className="p-3 rounded-lg border border-slate-700 bg-slate-950/60 space-y-3"><h4 className="font-black text-cyan-200">{editingEquipmentId ? 'EDIT EQUIPMENT' : 'ADD EQUIPMENT'}</h4>
          <label className="block">Type<select aria-label="Equipment type" value={equipmentDraft.kind} onChange={e => setEquipmentDraft({ ...equipmentDraft, kind: e.target.value as EquipmentKind })} className="mt-1 min-h-11 w-full bg-slate-900 border border-slate-700 rounded px-3">{EQUIPMENT_KINDS.map(kind => <option key={kind} value={kind}>{kind.replace('_', ' ')}</option>)}</select></label>
          <Text label="Equipment label" value={equipmentDraft.label} set={label => setEquipmentDraft({ ...equipmentDraft, label })} /><div className="grid grid-cols-2 gap-2"><Text label="Manufacturer" value={equipmentDraft.manufacturer ?? ''} set={manufacturer => setEquipmentDraft({ ...equipmentDraft, manufacturer })} /><Text label="Model" value={equipmentDraft.model ?? ''} set={model => setEquipmentDraft({ ...equipmentDraft, model })} /></div>
          <div className="grid grid-cols-3 gap-2"><Text label="Fact key" value={factKey} set={setFactKey} /><Text label="Fact value" value={factValue} set={setFactValue} /><Text label="Unit" value={factUnit} set={setFactUnit} /></div><button onClick={addFact} className="fo-control min-h-11 w-full rounded border"><Plus className="inline w-4 h-4" /> ADD FACT</button>{equipmentDraft.facts.map(fact => <div key={fact.key} className="text-[11px] text-slate-300">{fact.key}: <strong>{String(fact.value)} {fact.unit ?? ''}</strong></div>)}
          <Area label="Limitations (one per line)" value={equipmentDraft.limitations.join('\n')} set={value => setEquipmentDraft({ ...equipmentDraft, limitations: lines(value) })} /><Area label="Notes" value={equipmentDraft.notes ?? ''} set={notes => setEquipmentDraft({ ...equipmentDraft, notes })} /><button onClick={submitEquipment} className="min-h-11 w-full rounded bg-cyan-600 text-slate-950 font-black">SAVE EQUIPMENT</button>
        </section><RecordList records={equipment} edit={editEquipment} transition={async (id, restore) => { await transitionEquipment(id, restore); await reload(); }} />
      </div> : <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
        <section className="p-3 rounded-lg border border-slate-700 bg-slate-950/60 space-y-3"><h4 className="font-black text-cyan-200">{editingLoadoutId ? 'EDIT LOADOUT' : 'ADD LOADOUT'}</h4><Text label="Loadout name" value={loadoutDraft.name} set={name => setLoadoutDraft({ ...loadoutDraft, name })} /><Area label="Description" value={loadoutDraft.description ?? ''} set={description => setLoadoutDraft({ ...loadoutDraft, description })} />
          <label className="block">Equipment<select aria-label="Loadout equipment" value={selectedEquipmentId} onChange={e => setSelectedEquipmentId(e.target.value)} className="mt-1 min-h-11 w-full bg-slate-900 border border-slate-700 rounded px-3"><option value="">Select active equipment</option>{equipment.filter(item => item.state === 'active').map(item => <option key={item.equipmentId} value={item.equipmentId}>{item.label}</option>)}</select></label><div className="grid grid-cols-2 gap-2"><Text label="Role" value={selectedRole} set={setSelectedRole} /><label>Quantity<input aria-label="Quantity" type="number" min="1" max="99" value={selectedQuantity} onChange={e => setSelectedQuantity(Number(e.target.value))} className="mt-1 min-h-11 w-full bg-slate-900 border border-slate-700 rounded px-3" /></label></div><button onClick={addLoadoutItem} className="fo-control min-h-11 w-full rounded border"><Plus className="inline w-4 h-4" /> ADD TO LOADOUT</button>{loadoutDraft.items.map((item, index) => <div key={`${item.equipmentId}-${index}`} className="flex justify-between text-[11px] text-slate-300"><span>{equipment.find(candidate => candidate.equipmentId === item.equipmentId)?.label ?? item.equipmentId} · {item.role} × {item.quantity}</span><button aria-label="Remove loadout item" onClick={() => setLoadoutDraft({ ...loadoutDraft, items: loadoutDraft.items.filter((_, i) => i !== index) })}>REMOVE</button></div>)}<Area label="Limitations (one per line)" value={loadoutDraft.limitations.join('\n')} set={value => setLoadoutDraft({ ...loadoutDraft, limitations: lines(value) })} /><button onClick={submitLoadout} className="min-h-11 w-full rounded bg-cyan-600 text-slate-950 font-black">SAVE LOADOUT</button>
        </section><LoadoutList records={loadouts} equipment={equipment} edit={editLoadout} transition={async (id, restore) => { await transitionLoadout(id, restore); await reload(); }} />
      </div>}
      <p className="border-t border-cyan-800/60 pt-3 text-[11px] text-slate-300">Inventory and loadouts are operator records—not proof that equipment is packed, connected, functional, charged, licensed, or suitable.</p>
    </div>
  </div>;
};

const Text = ({ label, value, set }: { label: string; value: string; set: (value: string) => void }) => <label className="block">{label}<input aria-label={label} value={value} onChange={e => set(e.target.value)} className="mt-1 min-h-11 w-full bg-slate-900 border border-slate-700 rounded px-3" /></label>;
const Area = ({ label, value, set }: { label: string; value: string; set: (value: string) => void }) => <label className="block">{label}<textarea aria-label={label} value={value} onChange={e => set(e.target.value)} className="mt-1 min-h-16 w-full bg-slate-900 border border-slate-700 rounded p-3" /></label>;
const RecordList = ({ records, edit, transition }: { records: readonly EquipmentRecord[]; edit: (item: EquipmentRecord) => void; transition: (id: string, restore: boolean) => Promise<void> }) => <section className="space-y-2">{records.map(item => <article key={item.equipmentId} className={`p-3 rounded-lg border border-slate-700 bg-slate-950/60 ${item.state === 'deleted' ? 'opacity-60' : ''}`}><strong className="text-cyan-200">{item.label}</strong><span className="block text-[10px] text-slate-400">{item.kind} · {item.manufacturer ?? ''} {item.model ?? ''}</span><div className="mt-2 flex gap-2"><button onClick={() => edit(item)} disabled={item.state === 'deleted'} className="fo-control min-h-11 px-3 rounded border"><Pencil className="inline w-4 h-4" /> EDIT</button><button onClick={() => transition(item.equipmentId, item.state === 'deleted')} className="fo-control min-h-11 px-3 rounded border">{item.state === 'deleted' ? <ArchiveRestore className="inline w-4 h-4" /> : <Trash2 className="inline w-4 h-4" />} {item.state === 'deleted' ? 'RESTORE' : 'DELETE'}</button></div></article>)}</section>;
const LoadoutList = ({ records, equipment, edit, transition }: { records: readonly LoadoutRecord[]; equipment: readonly EquipmentRecord[]; edit: (item: LoadoutRecord) => void; transition: (id: string, restore: boolean) => Promise<void> }) => <section className="space-y-2">{records.map(item => <article key={item.loadoutId} className={`p-3 rounded-lg border border-slate-700 bg-slate-950/60 ${item.state === 'deleted' ? 'opacity-60' : ''}`}><strong className="text-cyan-200">{item.name}</strong>{item.items.map(entry => <span key={`${entry.equipmentId}-${entry.role}`} className="block text-[11px] text-slate-400">{equipment.find(candidate => candidate.equipmentId === entry.equipmentId)?.label ?? entry.equipmentId} · {entry.role} × {entry.quantity}</span>)}<div className="mt-2 flex gap-2"><button onClick={() => edit(item)} disabled={item.state === 'deleted'} className="fo-control min-h-11 px-3 rounded border"><Pencil className="inline w-4 h-4" /> EDIT</button><button onClick={() => transition(item.loadoutId, item.state === 'deleted')} className="fo-control min-h-11 px-3 rounded border">{item.state === 'deleted' ? 'RESTORE' : 'DELETE'}</button></div></article>)}</section>;
