import React, { useState } from 'react';
import type { Activation } from '../../server/activation';
import type { ActivationEntityState, OperationProgram } from '../../server/operationEntities';
import { updateActivationEntities } from '../activationApi';

export const OperationEntitiesPanel: React.FC<{ activation: Activation; onChange: (activation: Activation) => void }> = ({ activation, onChange }) => {
  const [program, setProgram] = useState<OperationProgram>('POTA'); const [reference, setReference] = useState(''); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null);
  const state: ActivationEntityState = activation.entityState ?? { schemaVersion: 1, entities: [], activeEntityIds: [] };
  const save = async (entityState: ActivationEntityState) => { setBusy(true); setMessage(null); const result = await updateActivationEntities(activation.activationId, { entityState }); if (result.kind === 'activation') onChange(result.activation); else setMessage(result.message); setBusy(false); };
  const add = async () => { if (!reference.trim()) return; setBusy(true); setMessage(null); const result = await updateActivationEntities(activation.activationId, { add: { program, reference } }); if (result.kind === 'activation') { onChange(result.activation); setReference(''); } else setMessage(result.message); setBusy(false); };
  const toggle = (entityId: string) => { const active = new Set(state.activeEntityIds); active.has(entityId) ? active.delete(entityId) : active.add(entityId); void save({ ...state, activeEntityIds: [...active] }); };
  return <section className="rounded border border-slate-700 bg-slate-950/50 p-2 space-y-2" aria-label="Operation entities"><div><h3 className="text-[10px] font-black uppercase text-cyan-300">OPERATION ENTITIES</h3><p className="text-[10px] text-slate-400">Active references are copied onto each new manual or WSJT-X QSO. Changing this set does not rewrite earlier QSOs.</p></div><div className="flex flex-wrap gap-2">{state.entities.map(entity => <label key={entity.entityId} className="flex min-h-11 items-center gap-2 rounded border border-slate-700 px-3 text-[11px] text-slate-200"><input type="checkbox" checked={state.activeEntityIds.includes(entity.entityId)} disabled={busy || activation.status === 'completed'} onChange={() => toggle(entity.entityId)} />{entity.program} {entity.reference}</label>)}{!state.entities.length && <span className="text-[11px] text-slate-500">No POTA or SOTA references.</span>}</div>{activation.status !== 'completed' && <div className="flex flex-wrap gap-2"><select aria-label="Entity program" value={program} onChange={event => setProgram(event.target.value as OperationProgram)} className="min-h-11 rounded border border-slate-700 bg-slate-950 px-2 text-[11px]"><option>POTA</option><option>SOTA</option></select><input aria-label="Entity reference" value={reference} onChange={event => setReference(event.target.value)} placeholder={program === 'POTA' ? 'US-1234' : 'W4V/SH-001'} className="min-h-11 rounded border border-slate-700 bg-slate-950 px-2 text-[11px]" /><button type="button" disabled={busy || !reference.trim()} onClick={() => void add()} className="min-h-11 rounded border border-cyan-700 px-3 text-[10px] font-bold text-cyan-200">ADD REFERENCE</button></div>}{message && <p role="alert" className="text-[11px] text-amber-200">{message}</p>}</section>;
};
