import React, { useEffect, useState } from 'react';
import type { Activation } from '../../server/activation';
import type { Qso } from '../../server/qso';
import { listQsos, updateQso } from '../qsoApi';

export const QsoAssociationsPanel: React.FC<{ activation: Activation }> = ({ activation }) => {
  const [qsos, setQsos] = useState<Qso[]>([]); const [selectedId, setSelectedId] = useState(''); const [message, setMessage] = useState<string | null>(null);
  const entities = activation.entityState?.entities ?? []; const selected = qsos.find(qso => qso.qsoId === selectedId);
  useEffect(() => { let cancelled = false; void (async () => { try { const result = await listQsos(activation.activationId); if (!cancelled) { setQsos(result.qsos); setSelectedId(current => current || result.qsos[0]?.qsoId || ''); } } catch { if (!cancelled) setMessage('QSO associations could not be loaded.'); } })(); return () => { cancelled = true; }; }, [activation.activationId]);
  if (!entities.length || !qsos.length) return null;
  const toggle = async (entityId: string) => { if (!selected) return; const entity = entities.find(item => item.entityId === entityId); if (!entity) return; const retained = selected.entityAssociations.entities.filter(item => item.entityId !== entityId && !(item.program === entity.program && item.reference === entity.reference)); const exists = retained.length !== selected.entityAssociations.entities.length; const entityAssociations = { schemaVersion: 1 as const, entities: exists ? retained : [...retained, { entityId, program: entity.program, reference: entity.reference, source: 'operator_edit' as const }] }; const result = await updateQso(activation.activationId, selected.qsoId, { entityAssociations }); if (result.kind === 'qso') { setQsos(values => values.map(qso => qso.qsoId === result.qso.qsoId ? result.qso : qso)); setMessage('QSO associations updated.'); } else setMessage(result.message); };
  return <section className="rounded border border-slate-700 bg-slate-950/50 p-2 space-y-2" aria-label="QSO entity associations"><h3 className="text-[10px] font-black uppercase text-cyan-300">EDIT QSO ASSOCIATIONS</h3><select aria-label="QSO to edit" value={selectedId} onChange={event => setSelectedId(event.target.value)} className="min-h-11 w-full rounded border border-slate-700 bg-slate-950 px-2 text-[11px]">{qsos.map(qso => <option key={qso.qsoId} value={qso.qsoId}>{qso.qsoDateTimeUtc} · {qso.callsign}</option>)}</select><div className="flex flex-wrap gap-2">{entities.map(entity => { const checked = selected?.entityAssociations.entities.some(item => item.entityId === entity.entityId || (item.program === entity.program && item.reference === entity.reference)) ?? false; return <label key={entity.entityId} className="flex min-h-11 items-center gap-2 rounded border border-slate-700 px-3 text-[11px]"><input type="checkbox" checked={checked} onChange={() => void toggle(entity.entityId)} />{entity.program} {entity.reference}</label>; })}</div><p className="text-[10px] text-slate-400">Association changes preserve the canonical QSO and do not change totals.</p>{message && <p role="status" className="text-[11px] text-amber-200">{message}</p>}</section>;
};
