import { useCallback, useEffect, useState } from 'react';
type SerialPort = { portName: string; friendlyName?: string | null; description?: string | null; vid?: string | null; pid?: string | null; serialNumber?: string | null; present: boolean };
type Inventory = { observedAtUtc: string; status: 'Ok' | 'Unavailable' | 'Error'; ports: SerialPort[]; error?: string | null };
export function SerialPortInventoryWidget() {
  const [inventory, setInventory] = useState<Inventory | null>(null); const [loading, setLoading] = useState(true);
  const refresh = useCallback(async () => { setLoading(true); try { const response = await fetch('/api/serial-ports'); if (!response.ok) throw new Error('Serial-port inventory unavailable.'); setInventory(await response.json() as Inventory); } catch (error) { setInventory({ observedAtUtc: new Date().toISOString(), status: 'Error', ports: [], error: error instanceof Error ? error.message : 'Serial-port inventory unavailable.' }); } finally { setLoading(false); } }, []);
  useEffect(() => { void refresh(); const timer = window.setInterval(() => void refresh(), 30000); return () => window.clearInterval(timer); }, [refresh]);
  return <section className="border border-slate-700 bg-slate-950/60 p-4 text-slate-100" aria-label="Serial ports"><div className="flex items-center justify-between"><h2 className="font-semibold">Serial ports</h2><button className="rounded border border-slate-600 px-2 py-1 text-xs" onClick={() => void refresh()} disabled={loading}>Refresh</button></div><p className="mt-2 text-sm text-slate-300">{loading ? 'Checking available ports…' : inventory?.status !== 'Ok' ? (inventory?.error ?? 'Unavailable') : `${inventory.ports.length} port${inventory.ports.length === 1 ? '' : 's'} detected`}</p>{!loading && inventory?.status === 'Ok' && inventory.ports.length === 0 && <p className="mt-2 text-xs text-slate-400">No serial ports detected.</p>}<div className="mt-3 space-y-2">{inventory?.ports.map(port => <div key={port.portName} className="rounded border border-slate-800 p-2 text-sm"><span className="font-mono">{port.portName}</span><span className="ml-3">{port.friendlyName ?? port.description ?? 'Metadata unavailable'}</span>{(port.vid || port.pid || port.serialNumber) && <span className="ml-3 text-xs text-slate-400">{[port.vid && `VID ${port.vid}`, port.pid && `PID ${port.pid}`, port.serialNumber && `S/N ${port.serialNumber}`].filter(Boolean).join(' · ')}</span>}</div>)}</div>{inventory && <p className="mt-3 text-xs text-slate-500">Last refresh: {new Date(inventory.observedAtUtc).toLocaleTimeString()}</p>}</section>;
}
