import type { Qso } from '../server/qso';

export type QsoApiResult = { readonly kind: 'qso'; readonly qso: Qso } | { readonly kind: 'qso_error'; readonly code: string; readonly message: string };
export interface QsoImportResult { readonly kind: 'qso_import'; readonly recordsFound: number; readonly imported: number; readonly skipped: number; readonly duplicates: number; readonly errors: readonly string[]; }
export async function listQsos(activationId: string): Promise<{ qsos: Qso[]; error?: string }> { const response = await fetch(`/api/activations/${encodeURIComponent(activationId)}/qsos`); const payload = await response.json(); return response.ok ? payload : { qsos: [], error: payload.message || 'QSOs could not be loaded.' }; }
export async function createQso(activationId: string, input: Record<string, unknown>): Promise<QsoApiResult> { return request(`/api/activations/${encodeURIComponent(activationId)}/qsos`, 'POST', input); }
export async function updateQso(activationId: string, qsoId: string, input: Record<string, unknown>): Promise<QsoApiResult> { return request(`/api/activations/${encodeURIComponent(activationId)}/qsos/${encodeURIComponent(qsoId)}`, 'PATCH', input); }
export async function deleteQso(activationId: string, qsoId: string): Promise<boolean> { const response = await fetch(`/api/activations/${encodeURIComponent(activationId)}/qsos/${encodeURIComponent(qsoId)}`, { method: 'DELETE' }); return response.ok; }
export async function importAdif(activationId: string, content: string): Promise<QsoImportResult | { readonly kind: 'qso_error'; readonly message: string }> { const response = await fetch(`/api/activations/${encodeURIComponent(activationId)}/qsos/import`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ content }) }); const payload = await response.json(); return response.ok ? payload : { kind: 'qso_error', message: payload.message || 'ADIF import failed.' }; }
async function request(path: string, method: 'POST' | 'PATCH', input: Record<string, unknown>): Promise<QsoApiResult> { const response = await fetch(path, { method, headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(input) }); const payload = await response.json(); return response.ok && payload.kind === 'qso' ? payload : { kind: 'qso_error', code: payload.code || 'request_failed', message: payload.message || 'The QSO could not be saved.' }; }
