import { describe, expect, it } from 'vitest';
import { assembleMissionGuidance } from '../missionGuidance';

const picture = (station = '2 matching reports from 2 unique receivers.', state: any = 'live', relationships: string[] = []) => ({ kind: 'layered_propagation_picture', layers: [{ id: 'modeled', label: 'MODELED PROPAGATION', state: 'retained', source: 'P.533', timing: 'retained', applicability: 'mission', summary: 'Representative strongest bands: 20m.', limitations: [] }, { id: 'environmental', label: 'ENVIRONMENT', state: 'retained', source: 'Open-Meteo', timing: 'retained', applicability: 'mission', summary: 'Retained.', limitations: [] }, { id: 'general_observed_rf', label: 'GENERAL OBSERVED RF', state, source: 'PSKReporter', timing: 'recent', applicability: 'regional', summary: '20 reports.', limitations: [] }, { id: 'station_signal', label: 'MY SIGNAL', state, source: 'PSKReporter', timing: 'recent', applicability: 'TX', summary: station, limitations: [] }], relationships, limitation: 'Separate evidence.' } as any);
const activation = (goal: string, extra: any = {}) => ({ schemaVersion: 2, activationId: 'a', type: 'POTA', status: 'active', startedAtUtc: '2026-09-05T12:00:00.000Z', actualTimingStatus: 'recorded', createdAtUtc: '2026-09-05T12:00:00.000Z', updatedAtUtc: '2026-09-05T12:00:00.000Z', operatingObjective: { goal, label: goal, ...extra } } as any);
const evaluate = (active: any, qsoCount: number, at = '2026-09-05T12:00:00.000Z', evidence = picture()) => assembleMissionGuidance({ activation: active, qsoCount, evaluatedAtUtc: at, picture: evidence, modeledBands: ['20m'], currentBand: '40m', currentMode: 'FT8' });

describe('mission-aware operating guidance', () => {
  it('uses reach-oriented evidence for chase DX with ample time', () => { const result = evaluate(activation('chase_dx', { deadlineUtc: '2026-09-05T14:00:00.000Z', deadlineBasis: 'operator_entered', deadlineProvenance: 'operator_entered' }), 2); expect(result).toMatchObject({ category: 'reach', urgency: 'routine', suggestedBand: '20m' }); expect(result.evidenceReferences).toEqual(['modeled', 'general_observed_rf', 'station_signal']); });
  it('preserves exploration after an activation is secured', () => { const result = evaluate(activation('explore_bands', { requiredQsoCount: 10, thresholdProvenance: 'program_default' }), 12); expect(result.category).toBe('exploration'); expect(result.action).toContain('band exploration'); expect(result.inputs.remainingQsos).toBe(0); expect(result.reasons).toContain('The recorded QSO threshold is already met; exploration remains the explicit objective.'); });
  it('shows 6/10 and thirty-minute qualification inputs', () => { const result = evaluate(activation('secure_activation', { requiredQsoCount: 10, thresholdProvenance: 'program_default', deadlineUtc: '2026-09-05T12:30:00.000Z', deadlineBasis: 'program_rule', deadlineProvenance: 'program_default' }), 6); expect(result).toMatchObject({ category: 'qualification', urgency: 'focused', inputs: { completedQsos: 6, requiredQsos: 10, remainingQsos: 4, minutesRemaining: 30, deadlineBasis: 'program_rule' } }); });
  it('changes urgency for 8/10 with ten minutes without guaranteeing completion', () => { const result = evaluate(activation('secure_activation', { requiredQsoCount: 10, thresholdProvenance: 'program_default', deadlineUtc: '2026-09-05T12:10:00.000Z', deadlineBasis: 'utc_rollover', deadlineProvenance: 'derived' }), 8); expect(result.urgency).toBe('urgent'); expect(result.inputs.remainingQsos).toBe(2); expect(result.limitations.join(' ')).toContain('not a prediction, guarantee'); });
  it('retains planning context when online evidence is stale', () => { const result = evaluate(activation('maximize_contacts'), 3, undefined, picture('Retained observation.', 'stale')); expect(result.reasons.join(' ')).toContain('Online evidence is degraded'); expect(result.evidenceReferences).toContain('modeled'); });
  it('preserves exact zero-report meaning without a failure score', () => { const result = evaluate(activation('secure_activation', { requiredQsoCount: 10, thresholdProvenance: 'program_default' }), 3, undefined, picture('No matching reports observed.')); expect(result.reasons).toContain('No matching reports observed. This is not a finding of bad propagation or station failure.'); expect(JSON.stringify(result)).not.toContain('score'); });
  it('exposes P.533/live disagreement without replacing either source', () => { const result = evaluate(activation('chase_dx'), 1, undefined, picture('Observed.', 'live', ['Current TX band differs from model.'])); expect(result.reasons.join(' ')).toContain('neither modeled nor observed evidence replaces the other'); expect(result.evidenceReferences).toContain('modeled'); expect(result.evidenceReferences).toContain('general_observed_rf'); });
  it('is byte-for-byte deterministic for identical inputs', () => { const active = activation('maximize_contacts'); expect(evaluate(active, 4)).toEqual(evaluate(active, 4)); });
});
